[workspace]
members = [
  "rusty_lr",
  "rusty_lr_core",
  "rusty_lr_derive",
  "rusty_lr_parser",
  "rusty_lr_buildscript",
  "rusty_lr_executable",
  "example/calculator",
  "example/calculator_u8",
  "example/lrtest", "example/glr", "example/json",
]
