
// This file was generated by rustylr 1.29.0
// This generated code is targeting rusty_lr version 3.36.0.
// There might be a build error if the version is not matched.
//
// ================================User Codes Begin================================
#[derive(Debug, Clone, Copy)]
pub enum Token {
    Num(i32),
    Plus,
    Star,
    LParen,
    RParen,
}
fn filter(term: &Token) -> &Token {
    term
}

// =================================User Codes End=================================
/*
====================================Grammar=====================================

# of terminal classes: 6
# of states: 13

0: A -> A plus A
1: A -> M
2: M -> M star M
3: M -> P
4: P -> num
5: P -> lparen E rparen
6: E -> A
7: Augmented -> E eof

*/
// =============================Generated Codes Begin==============================
/// type alias for `Context`
#[allow(non_camel_case_types, dead_code)]
pub type EContext = ::rusty_lr::parser::deterministic::Context<EDataStack, u8>;
/// type alias for CFG production rule
#[allow(non_camel_case_types, dead_code)]
pub type ERule = ::rusty_lr::rule::ProductionRule<ETerminalClasses, ENonTerminals>;
/// type alias for DFA state
#[allow(non_camel_case_types, dead_code)]
pub type EState = ::rusty_lr::parser::state::SparseState<
    ETerminalClasses,
    ENonTerminals,
    u8,
    u8,
>;
/// type alias for `ParseError`
#[allow(non_camel_case_types, dead_code)]
pub type EParseError = ::rusty_lr::parser::deterministic::ParseError<
    Token,
    ::rusty_lr::DefaultLocation,
    String,
>;
/// A enum that represents terminal classes
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord
)]
pub enum ETerminalClasses {
    num,
    plus,
    star,
    lparen,
    rparen,
    __rustylr_other_terminals,
    error,
    eof,
}
impl ::rusty_lr::parser::terminalclass::TerminalClass for ETerminalClasses {
    type Term = Token;
    const ERROR: Self = Self::error;
    const EOF: Self = Self::eof;
    fn as_str(&self) -> &'static str {
        match self {
            ETerminalClasses::num => "num",
            ETerminalClasses::plus => "plus",
            ETerminalClasses::star => "star",
            ETerminalClasses::lparen => "lparen",
            ETerminalClasses::rparen => "rparen",
            ETerminalClasses::__rustylr_other_terminals => "__rustylr_other_terminals",
            ETerminalClasses::error => "error",
            ETerminalClasses::eof => "eof",
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
    fn precedence(&self) -> ::rusty_lr::parser::Precedence {
        match self {
            ETerminalClasses::plus => ::rusty_lr::parser::Precedence::new(0),
            ETerminalClasses::star => ::rusty_lr::parser::Precedence::new(1),
            ETerminalClasses::eof => {
                unreachable!("eof token cannot be used in precedence levels")
            }
            _ => ::rusty_lr::parser::Precedence::none(),
        }
    }
    fn from_term(terminal: &Self::Term) -> Self {
        #[allow(unreachable_patterns)]
        match filter(terminal) {
            Token::Num(_) => ETerminalClasses::num,
            Token::Plus => ETerminalClasses::plus,
            Token::Star => ETerminalClasses::star,
            Token::LParen => ETerminalClasses::lparen,
            Token::RParen => ETerminalClasses::rparen,
            _ => ETerminalClasses::__rustylr_other_terminals,
        }
    }
}
impl std::fmt::Display for ETerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for ETerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
/// An enum that represents non-terminal symbols
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord
)]
pub enum ENonTerminals {
    A,
    M,
    P,
    E,
    Augmented,
}
impl std::fmt::Display for ENonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for ENonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl ::rusty_lr::parser::nonterminal::NonTerminal for ENonTerminals {
    fn as_str(&self) -> &'static str {
        match self {
            ENonTerminals::A => "A",
            ENonTerminals::M => "M",
            ENonTerminals::P => "P",
            ENonTerminals::E => "E",
            ENonTerminals::Augmented => "Augmented",
        }
    }
    fn is_trace(&self) -> bool {
        match self {
            ENonTerminals::A => false,
            ENonTerminals::M => false,
            ENonTerminals::P => false,
            ENonTerminals::E => false,
            ENonTerminals::Augmented => false,
        }
    }
    fn nonterm_type(&self) -> Option<::rusty_lr::parser::nonterminal::NonTerminalType> {
        match self {
            ENonTerminals::A => None,
            ENonTerminals::M => None,
            ENonTerminals::P => None,
            ENonTerminals::E => None,
            ENonTerminals::Augmented => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Augmented)
            }
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub enum EData {
    __terminals(Token),
    __variant1(i32),
    Empty,
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub struct EDataStack {
    pub __stack: Vec<EData>,
}
impl Default for EDataStack {
    fn default() -> Self {
        Self { __stack: Vec::new() }
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut,
    dead_code
)]
impl EDataStack {
    fn custom_reduce_action_0(
        mut M: i32,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<i32, String> {
        Ok({ M * 1 })
    }
    ///A -> A plus A
    #[inline]
    fn reduce_A_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), String> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant1(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::__variant1(_)))
            );
        }
        __location_stack.pop().unwrap();
        let mut a2 = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        __location_stack.pop().unwrap();
        let mut plus = match __data_stack.__stack.pop().unwrap() {
            EData::__terminals(val) => val,
            _ => unreachable!(),
        };
        __location_stack.pop().unwrap();
        let mut A = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            println!("{:?} {:?} {:?}", A, plus, a2);
            *data += 1;
            A + a2
        };
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///A -> M
    #[inline]
    fn reduce_A_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), String> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant1(_)))
            );
        }
        __location_stack.pop().unwrap();
        let mut M = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        let __res = M;
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///M -> M star M
    #[inline]
    fn reduce_M_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), String> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant1(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::__variant1(_)))
            );
        }
        __location_stack.pop().unwrap();
        let mut __rustylr_data_2 = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        __location_stack.pop().unwrap();
        __data_stack.__stack.pop().unwrap();
        __location_stack.pop().unwrap();
        let mut __rustylr_data_0 = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        let __rustylr_data_0 = Self::custom_reduce_action_0(
            __rustylr_data_0,
            data,
            __rustylr_location0,
        )?;
        let mut M_optim = __rustylr_data_0;
        let __rustylr_data_2 = Self::custom_reduce_action_0(
            __rustylr_data_2,
            data,
            __rustylr_location0,
        )?;
        let mut m2 = __rustylr_data_2;
        let __res = { M_optim * m2 };
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///P -> num
    #[inline]
    fn reduce_P_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), String> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__terminals(_)))
            );
        }
        __location_stack.pop().unwrap();
        let mut num = match __data_stack.__stack.pop().unwrap() {
            EData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            if let Token::Num(n) = num {
                n
            } else {
                return Err(format!("{:?}", num));
            }
        };
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///P -> lparen E rparen
    #[inline]
    fn reduce_P_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), String> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::__variant1(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::Empty))
            );
        }
        __location_stack.pop().unwrap();
        __data_stack.__stack.pop().unwrap();
        __location_stack.pop().unwrap();
        let mut E = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        __location_stack.pop().unwrap();
        __data_stack.__stack.pop().unwrap();
        let __res = E;
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///E -> A
    #[inline]
    fn reduce_E_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), String> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant1(_)))
            );
        }
        __location_stack.pop().unwrap();
        let mut A = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        let __res = A;
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    non_snake_case,
    non_camel_case_types,
    unused_variables
)]
impl ::rusty_lr::parser::data_stack::DataStack for EDataStack {
    type Term = Token;
    type NonTerm = ENonTerminals;
    type ReduceActionError = String;
    type UserData = i32;
    type StartType = i32;
    type Location = ::rusty_lr::DefaultLocation;
    fn pop_start(&mut self) -> Option<Self::StartType> {
        self.__stack.pop();
        match self.__stack.pop() {
            Some(EData::__variant1(val)) => Some(val),
            _ => None,
        }
    }
    fn pop(&mut self) {
        self.__stack.pop();
    }
    fn push_terminal(&mut self, term: Self::Term) {
        self.__stack.push(EData::__terminals(term));
    }
    fn push_empty(&mut self) {
        self.__stack.push(EData::Empty);
    }
    fn clear(&mut self) {
        self.__stack.clear();
    }
    fn reserve(&mut self, additional: usize) {
        self.__stack.reserve(additional);
    }
    fn split_off(&mut self, at: usize) -> Self {
        Self {
            __stack: self.__stack.split_off(at),
        }
    }
    fn truncate(&mut self, at: usize) {
        self.__stack.truncate(at);
    }
    fn append(&mut self, other: &mut Self) {
        self.__stack.append(&mut other.__stack);
    }
    fn reduce_action(
        data_stack: &mut Self,
        location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        push_data: bool,
        rule_index: usize,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Self::Term>,
        user_data: &mut Self::UserData,
        location0: &mut Self::Location,
    ) -> Result<(), Self::ReduceActionError> {
        match rule_index {
            0usize => {
                Self::reduce_A_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            1usize => {
                Self::reduce_A_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            2usize => {
                Self::reduce_M_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            4usize => {
                Self::reduce_P_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            5usize => {
                Self::reduce_P_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            6usize => {
                Self::reduce_E_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            _ => {
                unreachable!("Invalid Rule: {}", rule_index);
            }
        }
    }
}
/// A lightweight parser struct that references the static parser tables and production rules.
///
/// Since this struct only holds `'static` references to shared, read-only static parser tables,
/// it is extremely cheap to instantiate, copy, or clone, and takes very little space.
#[allow(unused_braces, unused_parens, unused_variables, non_snake_case, unused_mut)]
#[derive(Clone, Copy)]
pub struct EParser {
    /// production rules
    pub rules: &'static [ERule],
    /// states
    pub states: &'static [EState],
}
unsafe impl ::std::marker::Send for EParser {}
unsafe impl ::std::marker::Sync for EParser {}
#[rustfmt::skip]
impl ::rusty_lr::parser::Parser for EParser {
    type Term = Token;
    type TermClass = ETerminalClasses;
    type NonTerm = ENonTerminals;
    type State = EState;
    const ERROR_USED: bool = false;
    fn precedence_types(&self, level: u8) -> Option<::rusty_lr::rule::ReduceType> {
        #[allow(unreachable_patterns)]
        match level {
            0..=1 => Some(::rusty_lr::rule::ReduceType::Left),
            _ => None,
        }
    }
    fn get_rules(&self) -> &[ERule] {
        self.rules
    }
    fn get_states(&self) -> &[EState] {
        self.states
    }
}
/// Calculates the static parser tables from the grammar.
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, unused_variables, non_snake_case, unused_mut)]
impl EParser {
    /// Calculates the states and parser tables from the grammar.
    #[allow(clippy::clone_on_copy)]
    pub fn new() -> Self {
        static RULES: std::sync::OnceLock<Vec<ERule>> = std::sync::OnceLock::new();
        let rules = RULES
            .get_or_init(|| {
                vec![
                    ::rusty_lr::rule::ProductionRule { name : ENonTerminals::A, rule :
                    vec![::rusty_lr::Token::NonTerm(ENonTerminals::A),
                    ::rusty_lr::Token::Term(ETerminalClasses::plus),
                    ::rusty_lr::Token::NonTerm(ENonTerminals::A),], precedence :
                    Some(::rusty_lr::rule::Precedence::Fixed(0usize)), },
                    ::rusty_lr::rule::ProductionRule { name : ENonTerminals::A, rule :
                    vec![::rusty_lr::Token::NonTerm(ENonTerminals::M),], precedence :
                    None, }, ::rusty_lr::rule::ProductionRule { name : ENonTerminals::M,
                    rule : vec![::rusty_lr::Token::NonTerm(ENonTerminals::M),
                    ::rusty_lr::Token::Term(ETerminalClasses::star),
                    ::rusty_lr::Token::NonTerm(ENonTerminals::M),], precedence :
                    Some(::rusty_lr::rule::Precedence::Fixed(1usize)), },
                    ::rusty_lr::rule::ProductionRule { name : ENonTerminals::M, rule :
                    vec![::rusty_lr::Token::NonTerm(ENonTerminals::P),], precedence :
                    None, }, ::rusty_lr::rule::ProductionRule { name : ENonTerminals::P,
                    rule : vec![::rusty_lr::Token::Term(ETerminalClasses::num),],
                    precedence : None, }, ::rusty_lr::rule::ProductionRule { name :
                    ENonTerminals::P, rule :
                    vec![::rusty_lr::Token::Term(ETerminalClasses::lparen),
                    ::rusty_lr::Token::NonTerm(ENonTerminals::E),
                    ::rusty_lr::Token::Term(ETerminalClasses::rparen),], precedence :
                    None, }, ::rusty_lr::rule::ProductionRule { name : ENonTerminals::E,
                    rule : vec![::rusty_lr::Token::NonTerm(ENonTerminals::A),],
                    precedence : None, }, ::rusty_lr::rule::ProductionRule { name :
                    ENonTerminals::Augmented, rule :
                    vec![::rusty_lr::Token::NonTerm(ENonTerminals::E),
                    ::rusty_lr::Token::Term(ETerminalClasses::eof),], precedence : None,
                    },
                ]
            });
        static STATES: std::sync::OnceLock<Vec<EState>> = std::sync::OnceLock::new();
        let states = STATES
            .get_or_init(|| {
                let states: Vec<
                    ::rusty_lr::parser::state::IntermediateState<
                        ETerminalClasses,
                        ENonTerminals,
                        u8,
                        u8,
                    >,
                > = vec![
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::num,
                    ::rusty_lr::parser::state::ShiftTarget::new(1, true)),
                    (ETerminalClasses::lparen,
                    ::rusty_lr::parser::state::ShiftTarget::new(2, false)),],
                    shift_goto_map_nonterm : vec![(ENonTerminals::A,
                    ::rusty_lr::parser::state::ShiftTarget::new(3, true)),
                    (ENonTerminals::M, ::rusty_lr::parser::state::ShiftTarget::new(6,
                    true)), (ENonTerminals::P,
                    ::rusty_lr::parser::state::ShiftTarget::new(6, true)),
                    (ENonTerminals::E, ::rusty_lr::parser::state::ShiftTarget::new(11,
                    true)),], reduce_map : Default::default(), ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 0 as usize, shifted :
                    0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 1 as usize,
                    shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 2
                    as usize, shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef {
                    rule : 3 as usize, shifted : 0 as usize, },
                    ::rusty_lr::rule::ShiftedRuleRef { rule : 4 as usize, shifted : 0 as
                    usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 5 as usize,
                    shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 6
                    as usize, shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef {
                    rule : 7 as usize, shifted : 0 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![], shift_goto_map_nonterm : vec![], reduce_map :
                    vec![(ETerminalClasses::plus, vec![4]), (ETerminalClasses::star,
                    vec![4]), (ETerminalClasses::rparen, vec![4]),
                    (ETerminalClasses::eof, vec![4]),], ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 4 as usize, shifted :
                    1 as usize, },], can_accept_error : ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::num,
                    ::rusty_lr::parser::state::ShiftTarget::new(1, true)),
                    (ETerminalClasses::lparen,
                    ::rusty_lr::parser::state::ShiftTarget::new(2, false)),],
                    shift_goto_map_nonterm : vec![(ENonTerminals::A,
                    ::rusty_lr::parser::state::ShiftTarget::new(3, true)),
                    (ENonTerminals::M, ::rusty_lr::parser::state::ShiftTarget::new(6,
                    true)), (ENonTerminals::P,
                    ::rusty_lr::parser::state::ShiftTarget::new(6, true)),
                    (ENonTerminals::E, ::rusty_lr::parser::state::ShiftTarget::new(9,
                    true)),], reduce_map : Default::default(), ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 0 as usize, shifted :
                    0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 1 as usize,
                    shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 2
                    as usize, shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef {
                    rule : 3 as usize, shifted : 0 as usize, },
                    ::rusty_lr::rule::ShiftedRuleRef { rule : 4 as usize, shifted : 0 as
                    usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 5 as usize,
                    shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 5
                    as usize, shifted : 1 as usize, }, ::rusty_lr::rule::ShiftedRuleRef {
                    rule : 6 as usize, shifted : 0 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::plus,
                    ::rusty_lr::parser::state::ShiftTarget::new(4, true)),],
                    shift_goto_map_nonterm : vec![], reduce_map :
                    vec![(ETerminalClasses::rparen, vec![6]), (ETerminalClasses::eof,
                    vec![6]),], ruleset : vec![::rusty_lr::rule::ShiftedRuleRef { rule :
                    0 as usize, shifted : 1 as usize, }, ::rusty_lr::rule::ShiftedRuleRef
                    { rule : 6 as usize, shifted : 1 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::num,
                    ::rusty_lr::parser::state::ShiftTarget::new(1, true)),
                    (ETerminalClasses::lparen,
                    ::rusty_lr::parser::state::ShiftTarget::new(2, false)),],
                    shift_goto_map_nonterm : vec![(ENonTerminals::A,
                    ::rusty_lr::parser::state::ShiftTarget::new(5, true)),
                    (ENonTerminals::M, ::rusty_lr::parser::state::ShiftTarget::new(6,
                    true)), (ENonTerminals::P,
                    ::rusty_lr::parser::state::ShiftTarget::new(6, true)),], reduce_map :
                    Default::default(), ruleset : vec![::rusty_lr::rule::ShiftedRuleRef {
                    rule : 0 as usize, shifted : 0 as usize, },
                    ::rusty_lr::rule::ShiftedRuleRef { rule : 0 as usize, shifted : 2 as
                    usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 1 as usize,
                    shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 2
                    as usize, shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef {
                    rule : 3 as usize, shifted : 0 as usize, },
                    ::rusty_lr::rule::ShiftedRuleRef { rule : 4 as usize, shifted : 0 as
                    usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 5 as usize,
                    shifted : 0 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![], shift_goto_map_nonterm : vec![], reduce_map :
                    vec![(ETerminalClasses::plus, vec![0]), (ETerminalClasses::rparen,
                    vec![0]), (ETerminalClasses::eof, vec![0]),], ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 0 as usize, shifted :
                    3 as usize, },], can_accept_error : ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::star,
                    ::rusty_lr::parser::state::ShiftTarget::new(7, false)),],
                    shift_goto_map_nonterm : vec![], reduce_map :
                    vec![(ETerminalClasses::plus, vec![1]), (ETerminalClasses::rparen,
                    vec![1]), (ETerminalClasses::eof, vec![1]),], ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 1 as usize, shifted :
                    1 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 2 as usize,
                    shifted : 1 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::num,
                    ::rusty_lr::parser::state::ShiftTarget::new(1, true)),
                    (ETerminalClasses::lparen,
                    ::rusty_lr::parser::state::ShiftTarget::new(2, false)),],
                    shift_goto_map_nonterm : vec![(ENonTerminals::M,
                    ::rusty_lr::parser::state::ShiftTarget::new(8, true)),
                    (ENonTerminals::P, ::rusty_lr::parser::state::ShiftTarget::new(8,
                    true)),], reduce_map : Default::default(), ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 2 as usize, shifted :
                    0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 2 as usize,
                    shifted : 2 as usize, }, ::rusty_lr::rule::ShiftedRuleRef { rule : 3
                    as usize, shifted : 0 as usize, }, ::rusty_lr::rule::ShiftedRuleRef {
                    rule : 4 as usize, shifted : 0 as usize, },
                    ::rusty_lr::rule::ShiftedRuleRef { rule : 5 as usize, shifted : 0 as
                    usize, },], can_accept_error : ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![], shift_goto_map_nonterm : vec![], reduce_map :
                    vec![(ETerminalClasses::plus, vec![2]), (ETerminalClasses::star,
                    vec![2]), (ETerminalClasses::rparen, vec![2]),
                    (ETerminalClasses::eof, vec![2]),], ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 2 as usize, shifted :
                    3 as usize, },], can_accept_error : ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::rparen,
                    ::rusty_lr::parser::state::ShiftTarget::new(10, false)),],
                    shift_goto_map_nonterm : vec![], reduce_map : Default::default(),
                    ruleset : vec![::rusty_lr::rule::ShiftedRuleRef { rule : 5 as usize,
                    shifted : 2 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![], shift_goto_map_nonterm : vec![], reduce_map :
                    vec![(ETerminalClasses::plus, vec![5]), (ETerminalClasses::star,
                    vec![5]), (ETerminalClasses::rparen, vec![5]),
                    (ETerminalClasses::eof, vec![5]),], ruleset :
                    vec![::rusty_lr::rule::ShiftedRuleRef { rule : 5 as usize, shifted :
                    3 as usize, },], can_accept_error : ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![(ETerminalClasses::eof,
                    ::rusty_lr::parser::state::ShiftTarget::new(12, true)),],
                    shift_goto_map_nonterm : vec![], reduce_map : Default::default(),
                    ruleset : vec![::rusty_lr::rule::ShiftedRuleRef { rule : 7 as usize,
                    shifted : 1 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                    ::rusty_lr::parser::state::IntermediateState { shift_goto_map_term :
                    vec![], shift_goto_map_nonterm : vec![], reduce_map :
                    Default::default(), ruleset : vec![::rusty_lr::rule::ShiftedRuleRef {
                    rule : 7 as usize, shifted : 2 as usize, },], can_accept_error :
                    ::rusty_lr::TriState::False, },
                ];
                states.into_iter().map(|state| state.into()).collect()
            });
        Self {
            rules: rules.as_slice(),
            states: states.as_slice(),
        }
    }
}

// ==============================Generated Codes End===============================
        