
// This file was generated by rustylr 1.32.0
// This generated code is targeting rusty_lr version 4.1.0.
// There might be a build error if the version is not matched.
//
// ================================User Codes Begin================================

// =================================User Codes End=================================
/*
====================================Grammar=====================================

# of terminal classes: 9
# of states: 25

0: Digit -> '0'
1: Digit -> ['1', '2', ..., '6'-'9']
2: Number -> ' '* Digit+ ' '*
3: P -> Number
4: P -> ' '* '(' E ')' ' '*
5: E -> E Op E
6: E -> ' '* '-' E
7: E -> P
8: Op -> '+'
9: Op -> '*'
10: ' '+ -> ' '
11: ' '+ -> ' '+ ' '
12: ' '* -> ' '+
13: ' '* -> 
14: Digit+ -> Digit
15: Digit+ -> Digit+ Digit
16: Augmented -> E eof

*/
// =============================Generated Codes Begin==============================
/// type alias for `Context`
#[allow(non_camel_case_types, dead_code)]
pub type EContext = ::rusty_lr::parser::deterministic::Context<EParser, EDataStack, u8>;
/// type alias for CFG production rule
#[allow(non_camel_case_types, dead_code)]
pub type ERule = ::rusty_lr::rule::ProductionRule<ETerminalClasses, ENonTerminals>;
/// type alias for runtime parser tables
#[allow(non_camel_case_types, dead_code)]
pub type ETables = ::rusty_lr::parser::table::DenseFlatTables<
    ETerminalClasses,
    ENonTerminals,
    u8,
    u8,
>;
/// type alias for `ParseError`
#[allow(non_camel_case_types, dead_code)]
pub type EParseError = ::rusty_lr::parser::deterministic::ParseError<
    char,
    ::rusty_lr::DefaultLocation,
    ::rusty_lr::DefaultReduceActionError,
>;
/// A enum that represents terminal classes
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord
)]
#[repr(usize)]
pub enum ETerminalClasses {
    TermClass0,
    TermClass1,
    TermClass2,
    TermClass3,
    TermClass4,
    TermClass5,
    TermClass6,
    TermClass7,
    TermClass8,
    error,
    eof,
}
impl ETerminalClasses {
    #[inline]
    pub fn from_usize(value: usize) -> Self {
        debug_assert!(
            value < 11usize, "Terminal class index {} is out of bounds (max {})", value,
            11usize
        );
        unsafe { ::std::mem::transmute(value) }
    }
}
impl ::rusty_lr::parser::terminalclass::TerminalClass for ETerminalClasses {
    type Term = char;
    const ERROR: Self = Self::error;
    const EOF: Self = Self::eof;
    fn as_str(&self) -> &'static str {
        match self {
            ETerminalClasses::TermClass0 => "' '",
            ETerminalClasses::TermClass1 => "<Others>",
            ETerminalClasses::TermClass2 => "'('",
            ETerminalClasses::TermClass3 => "')'",
            ETerminalClasses::TermClass4 => "'-'",
            ETerminalClasses::TermClass5 => "'0'",
            ETerminalClasses::TermClass6 => "['1', '2', ..., '6'-'9']",
            ETerminalClasses::TermClass7 => "'*'",
            ETerminalClasses::TermClass8 => "'+'",
            ETerminalClasses::error => "error",
            ETerminalClasses::eof => "eof",
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
    fn precedence(&self) -> ::rusty_lr::parser::Precedence {
        match self {
            ETerminalClasses::TermClass8 => ::rusty_lr::parser::Precedence::new(0),
            ETerminalClasses::TermClass7 => ::rusty_lr::parser::Precedence::new(1),
            ETerminalClasses::eof => {
                unreachable!("eof token cannot be used in precedence levels")
            }
            _ => ::rusty_lr::parser::Precedence::none(),
        }
    }
    fn from_term(terminal: &Self::Term) -> Self {
        #[allow(unreachable_patterns, unused_variables)]
        match terminal {
            ' ' => ETerminalClasses::TermClass0,
            '(' => ETerminalClasses::TermClass2,
            ')' => ETerminalClasses::TermClass3,
            '-' => ETerminalClasses::TermClass4,
            '0' => ETerminalClasses::TermClass5,
            '1'..='9' => ETerminalClasses::TermClass6,
            '*' => ETerminalClasses::TermClass7,
            '+' => ETerminalClasses::TermClass8,
            _ => ETerminalClasses::TermClass1,
        }
    }
}
impl std::fmt::Display for ETerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for ETerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
/// An enum that represents non-terminal symbols
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord
)]
#[repr(usize)]
pub enum ENonTerminals {
    Digit,
    Number,
    P,
    E,
    Op,
    __LiteralChar0Plus6,
    __LiteralChar0Star7,
    _DigitPlus9,
    Augmented,
}
impl ENonTerminals {
    #[inline]
    pub fn from_usize(value: usize) -> Self {
        debug_assert!(
            value < 9usize, "Non-terminal index {} is out of bounds (max {})", value,
            9usize
        );
        unsafe { ::std::mem::transmute(value) }
    }
}
impl std::fmt::Display for ENonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for ENonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl ::rusty_lr::parser::nonterminal::NonTerminal for ENonTerminals {
    fn as_str(&self) -> &'static str {
        match self {
            ENonTerminals::Digit => "Digit",
            ENonTerminals::Number => "Number",
            ENonTerminals::P => "P",
            ENonTerminals::E => "E",
            ENonTerminals::Op => "Op",
            ENonTerminals::__LiteralChar0Plus6 => "' '+",
            ENonTerminals::__LiteralChar0Star7 => "' '*",
            ENonTerminals::_DigitPlus9 => "Digit+",
            ENonTerminals::Augmented => "Augmented",
        }
    }
    fn nonterm_type(&self) -> Option<::rusty_lr::parser::nonterminal::NonTerminalType> {
        match self {
            ENonTerminals::Digit => None,
            ENonTerminals::Number => None,
            ENonTerminals::P => None,
            ENonTerminals::E => None,
            ENonTerminals::Op => None,
            ENonTerminals::__LiteralChar0Plus6 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusLeft)
            }
            ENonTerminals::__LiteralChar0Star7 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Star)
            }
            ENonTerminals::_DigitPlus9 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusLeft)
            }
            ENonTerminals::Augmented => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Augmented)
            }
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub enum EData {
    __terminals(char),
    __variant1(i32),
    __variant2(f32),
    __variant3(Vec<char>),
    Empty,
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub struct EDataStack {
    pub __stack: Vec<EData>,
}
impl Default for EDataStack {
    fn default() -> Self {
        Self { __stack: Vec::new() }
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut,
    dead_code
)]
impl EDataStack {
    ///Digit -> '0'
    #[inline]
    fn reduce_Digit_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        let __res = { '0' };
        if __push_data {
            __data_stack.__stack.push(EData::__terminals(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///Number -> ' '* Digit+ ' '*
    #[inline]
    fn reduce_Number_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::__variant3(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.pop();
        let mut Digit = match __data_stack.__stack.pop().unwrap() {
            EData::__variant3(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.pop();
        let __res = { Digit.into_iter().collect::<String>().parse().unwrap() };
        if __push_data {
            __data_stack.__stack.push(EData::__variant1(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///P -> Number
    #[inline]
    fn reduce_P_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant1(_)))
            );
        }
        __location_stack.pop();
        let mut Number = match __data_stack.__stack.pop().unwrap() {
            EData::__variant1(val) => val,
            _ => unreachable!(),
        };
        let __res = { Number as f32 };
        if __push_data {
            __data_stack.__stack.push(EData::__variant2(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///P -> ' '* '(' E ')' ' '*
    #[inline]
    fn reduce_P_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                4usize), Some(& EData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 5);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        let mut E = match __data_stack.__stack.pop().unwrap() {
            EData::__variant2(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        let __res = E;
        if __push_data {
            __data_stack.__stack.push(EData::__variant2(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///E -> E Op E
    #[inline]
    fn reduce_E_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::__variant2(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        let mut e2 = match __data_stack.__stack.pop().unwrap() {
            EData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let mut Op = match __data_stack.__stack.pop().unwrap() {
            EData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let mut E = match __data_stack.__stack.pop().unwrap() {
            EData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            *data += 1;
            println!("{:?} {:?} {:?}", E, Op, e2);
            match Op {
                '+' => E + e2,
                '*' => E * e2,
                _ => panic!("Unknown operator: {:?}", Op),
            }
        };
        if __push_data {
            __data_stack.__stack.push(EData::__variant2(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///E -> ' '* '-' E
    #[inline]
    fn reduce_E_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& EData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        let mut E = match __data_stack.__stack.pop().unwrap() {
            EData::__variant2(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        let __res = { -E };
        if __push_data {
            __data_stack.__stack.push(EData::__variant2(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///' '+ -> ' '+ ' '
    #[inline]
    fn reduce___LiteralChar0Plus6_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(EData::Empty);
        Ok(())
    }
    ///' '* -> ' '+
    #[inline]
    fn reduce___LiteralChar0Star7_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        __data_stack.__stack.push(EData::Empty);
        Ok(())
    }
    ///' '* ->
    #[inline]
    fn reduce___LiteralChar0Star7_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        __data_stack.__stack.push(EData::Empty);
        Ok(())
    }
    ///Digit+ -> Digit
    #[inline]
    fn reduce__DigitPlus9_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__terminals(_)))
            );
        }
        __location_stack.pop();
        let mut A = match __data_stack.__stack.pop().unwrap() {
            EData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let __res = { vec![A] };
        if __push_data {
            __data_stack.__stack.push(EData::__variant3(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
    ///Digit+ -> Digit+ Digit
    #[inline]
    fn reduce__DigitPlus9_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut i32,
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& EData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& EData::__variant3(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut A = match __data_stack.__stack.pop().unwrap() {
            EData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let mut Ap = match __data_stack.__stack.pop().unwrap() {
            EData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            Ap.push(A);
            Ap
        };
        if __push_data {
            __data_stack.__stack.push(EData::__variant3(__res));
        } else {
            __data_stack.__stack.push(EData::Empty);
        }
        Ok(())
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    non_snake_case,
    non_camel_case_types,
    unused_variables
)]
impl ::rusty_lr::parser::data_stack::DataStack for EDataStack {
    type Term = char;
    type NonTerm = ENonTerminals;
    type ReduceActionError = ::rusty_lr::DefaultReduceActionError;
    type UserData = i32;
    type StartType = f32;
    type Location = ::rusty_lr::DefaultLocation;
    fn pop_start(&mut self) -> Option<Self::StartType> {
        self.__stack.pop();
        match self.__stack.pop() {
            Some(EData::__variant2(val)) => Some(val),
            _ => None,
        }
    }
    fn pop(&mut self) {
        self.__stack.pop();
    }
    fn push_terminal(&mut self, term: Self::Term) {
        self.__stack.push(EData::__terminals(term));
    }
    fn push_empty(&mut self) {
        self.__stack.push(EData::Empty);
    }
    fn clear(&mut self) {
        self.__stack.clear();
    }
    fn reserve(&mut self, additional: usize) {
        self.__stack.reserve(additional);
    }
    fn split_off(&mut self, at: usize) -> Self {
        Self {
            __stack: self.__stack.split_off(at),
        }
    }
    fn truncate(&mut self, at: usize) {
        self.__stack.truncate(at);
    }
    fn append(&mut self, other: &mut Self) {
        self.__stack.append(&mut other.__stack);
    }
    fn reduce_action(
        data_stack: &mut Self,
        location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        push_data: bool,
        rule_index: usize,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Self::Term>,
        user_data: &mut Self::UserData,
        location0: &mut Self::Location,
    ) -> Result<(), Self::ReduceActionError> {
        match rule_index {
            0usize => {
                Self::reduce_Digit_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            2usize => {
                Self::reduce_Number_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            3usize => {
                Self::reduce_P_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            4usize => {
                Self::reduce_P_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            5usize => {
                Self::reduce_E_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            6usize => {
                Self::reduce_E_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            11usize => {
                Self::reduce___LiteralChar0Plus6_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            12usize => {
                Self::reduce___LiteralChar0Star7_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            13usize => {
                Self::reduce___LiteralChar0Star7_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            14usize => {
                Self::reduce__DigitPlus9_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            15usize => {
                Self::reduce__DigitPlus9_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            _ => {
                unreachable!("Invalid Rule: {}", rule_index);
            }
        }
    }
}
/// A lightweight parser struct that references the static parser tables and production rules.
///
/// Since this struct only holds `'static` references to shared, read-only static parser tables,
/// it is extremely cheap to instantiate, copy, or clone, and takes very little space.
#[allow(unused_braces, unused_parens, unused_variables, non_snake_case, unused_mut)]
#[derive(Clone, Copy)]
pub struct EParser;
unsafe impl ::std::marker::Send for EParser {}
unsafe impl ::std::marker::Sync for EParser {}
#[rustfmt::skip]
impl ::rusty_lr::parser::Parser for EParser {
    type Term = char;
    type TermClass = ETerminalClasses;
    type NonTerm = ENonTerminals;
    type StateIndex = u8;
    type ReduceRules = u8;
    type Tables = ETables;
    const ERROR_USED: bool = false;
    fn precedence_types(level: u8) -> Option<::rusty_lr::rule::ReduceType> {
        #[allow(unreachable_patterns)]
        match level {
            0..=1 => Some(::rusty_lr::rule::ReduceType::Left),
            _ => None,
        }
    }
    fn get_tables() -> &'static ETables {
        static TABLES: std::sync::OnceLock<ETables> = std::sync::OnceLock::new();
        TABLES
            .get_or_init(|| {
                static RULE_NAMES: &[u32] = &[
                    0, 0, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8,
                ];
                static RULE_PRECEDENCES: &[u32] = &[
                    0, 0, 0, 0, 0, 6, 9, 0, 1, 5, 0, 0, 0, 0, 0, 0, 0,
                ];
                static RULE_LENGTHS: &[u32] = &[
                    1, 1, 3, 1, 5, 3, 3, 1, 1, 1, 1, 2, 1, 0, 1, 2, 2,
                ];
                static SHIFT_TERM_DATA: &[u32] = &[
                    196608, 2147614727, 2147614728, 2147581962, 196608, 2147614727,
                    2147614728, 229376, 294914, 753668, 589829, 2148106246, 196608,
                    360451, 2147909639, 2147909640, 196608, 196608, 2147909639,
                    2147909640, 294914, 524292, 589829, 2148106246, 196608, 196608,
                    589829, 2148171782, 196608,
                ];
                static SHIFT_TERM_OFFSETS: &[u32] = &[
                    0, 1, 1, 4, 4, 5, 7, 8, 8, 12, 13, 16, 17, 17, 18, 20, 24, 25, 25,
                    25, 25, 28, 28, 28, 29, 29,
                ];
                static SHIFT_NONTERM_DATA: &[u32] = &[
                    2147516417, 2147549186, 2147549187, 2147680261, 2147745798,
                    2147614724, 2147516417, 2147647490, 2147647491, 2147680261,
                    2147745798, 2147614724, 2148106240, 2148139015, 2147516417,
                    2147811330, 2147811331, 2147680261, 2147975174, 2147909636,
                    2147680261, 2147876870, 2147516417, 2147942402, 2147942403,
                    2147680261, 2147975174, 2147909636, 2148106240, 2148139015,
                    2147516417, 2148040706, 2148040707, 2147680261, 2147975174,
                    2147909636, 2148171776, 2147680261, 2148204550, 2147516417,
                    2148270082, 2148270083, 2147680261, 2147745798, 2147614724,
                ];
                static SHIFT_NONTERM_OFFSETS: &[u32] = &[
                    0, 5, 5, 6, 6, 11, 12, 12, 12, 14, 19, 20, 22, 22, 27, 28, 30, 35,
                    36, 36, 36, 39, 39, 39, 44, 45,
                ];
                static REDUCE_DATA: &[u32] = &[
                    2, 1, 13, 4, 1, 13, 5, 1, 13, 6, 1, 13, 3, 1, 3, 7, 1, 3, 8, 1, 3,
                    10, 1, 3, 2, 1, 13, 4, 1, 13, 5, 1, 13, 6, 1, 13, 7, 1, 5, 8, 1, 5,
                    10, 1, 5, 2, 1, 12, 3, 1, 12, 4, 1, 12, 5, 1, 12, 6, 1, 12, 7, 1, 12,
                    8, 1, 12, 10, 1, 12, 0, 1, 11, 2, 1, 11, 3, 1, 11, 4, 1, 11, 5, 1,
                    11, 6, 1, 11, 7, 1, 11, 8, 1, 11, 10, 1, 11, 2, 1, 13, 4, 1, 13, 5,
                    1, 13, 6, 1, 13, 3, 1, 13, 7, 1, 13, 8, 1, 13, 10, 1, 13, 3, 1, 4, 7,
                    1, 4, 8, 1, 4, 10, 1, 4, 2, 1, 13, 4, 1, 13, 5, 1, 13, 6, 1, 13, 3,
                    1, 5, 7, 1, 5, 8, 1, 5, 2, 1, 13, 4, 1, 13, 5, 1, 13, 6, 1, 13, 3, 1,
                    6, 7, 1, 6, 8, 1, 6, 0, 1, 0, 3, 1, 0, 5, 1, 0, 6, 1, 0, 7, 1, 0, 8,
                    1, 0, 10, 1, 0, 0, 1, 14, 3, 1, 14, 5, 1, 14, 6, 1, 14, 7, 1, 14, 8,
                    1, 14, 10, 1, 14, 3, 1, 13, 7, 1, 13, 8, 1, 13, 10, 1, 13, 0, 1, 15,
                    3, 1, 15, 5, 1, 15, 6, 1, 15, 7, 1, 15, 8, 1, 15, 10, 1, 15, 3, 1, 2,
                    7, 1, 2, 8, 1, 2, 10, 1, 2, 2, 1, 13, 4, 1, 13, 5, 1, 13, 6, 1, 13,
                    7, 1, 6, 8, 1, 6, 10, 1, 6,
                ];
                static REDUCE_OFFSETS: &[u32] = &[
                    0, 12, 24, 24, 24, 36, 45, 69, 96, 96, 108, 108, 120, 132, 144, 153,
                    153, 165, 174, 195, 216, 228, 249, 261, 273, 282,
                ];
                static CAN_ACCEPT_ERROR: &[u8] = &[
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0,
                ];
                let num_rules = 17usize;
                let mut rules = Vec::with_capacity(num_rules);
                for i in 0..num_rules {
                    let name = ENonTerminals::from_usize(RULE_NAMES[i] as usize);
                    let prec_val = RULE_PRECEDENCES[i];
                    let precedence = match prec_val & 3 {
                        0 => ::rusty_lr::rule::Precedence::None,
                        1 => {
                            ::rusty_lr::rule::Precedence::Fixed((prec_val >> 2) as usize)
                        }
                        2 => {
                            ::rusty_lr::rule::Precedence::Dynamic(
                                (prec_val >> 2) as usize,
                            )
                        }
                        _ => unreachable!(),
                    };
                    rules
                        .push(::rusty_lr::parser::table::RuleInfo {
                            name,
                            len: RULE_LENGTHS[i] as usize,
                            precedence,
                        });
                }
                let num_states = 25usize;
                let mut state_rows = Vec::with_capacity(num_states);
                for i in 0..num_states {
                    let term_start = SHIFT_TERM_OFFSETS[i] as usize;
                    let term_end = SHIFT_TERM_OFFSETS[i + 1] as usize;
                    let mut shift_goto_map_term = Vec::with_capacity(
                        term_end - term_start,
                    );
                    for idx in term_start..term_end {
                        let val = SHIFT_TERM_DATA[idx];
                        let term_class = ETerminalClasses::from_usize(
                            (val & 0x7fff) as usize,
                        );
                        let state = ((val >> 15) & 0xffff) as usize;
                        let push = (val >> 31) != 0;
                        shift_goto_map_term
                            .push((
                                term_class,
                                ::rusty_lr::parser::table::ShiftTarget::new(state, push),
                            ));
                    }
                    let nonterm_start = SHIFT_NONTERM_OFFSETS[i] as usize;
                    let nonterm_end = SHIFT_NONTERM_OFFSETS[i + 1] as usize;
                    let mut shift_goto_map_nonterm = Vec::with_capacity(
                        nonterm_end - nonterm_start,
                    );
                    for idx in nonterm_start..nonterm_end {
                        let val = SHIFT_NONTERM_DATA[idx];
                        let nonterm = ENonTerminals::from_usize((val & 0x7fff) as usize);
                        let state = ((val >> 15) & 0xffff) as usize;
                        let push = (val >> 31) != 0;
                        shift_goto_map_nonterm
                            .push((
                                nonterm,
                                ::rusty_lr::parser::table::ShiftTarget::new(state, push),
                            ));
                    }
                    let reduce_start = REDUCE_OFFSETS[i] as usize;
                    let reduce_end = REDUCE_OFFSETS[i + 1] as usize;
                    let mut reduce_map = Vec::new();
                    let mut idx = reduce_start;
                    while idx < reduce_end {
                        let term_val = REDUCE_DATA[idx];
                        let term_class = ETerminalClasses::from_usize(term_val as usize);
                        let len = REDUCE_DATA[idx + 1] as usize;
                        let mut rules = Vec::with_capacity(len);
                        for r_idx in 0..len {
                            rules.push(REDUCE_DATA[idx + 2 + r_idx] as usize);
                        }
                        reduce_map.push((term_class, rules));
                        idx += 2 + len;
                    }
                    let can_accept_error = match CAN_ACCEPT_ERROR[i] {
                        0 => ::rusty_lr::TriState::False,
                        1 => ::rusty_lr::TriState::True,
                        2 => ::rusty_lr::TriState::Maybe,
                        _ => unreachable!(),
                    };
                    let intermediate = ::rusty_lr::parser::state::IntermediateState {
                        shift_goto_map_term,
                        shift_goto_map_nonterm,
                        reduce_map,
                        ruleset: Vec::new(),
                        can_accept_error,
                    };
                    state_rows.push(intermediate);
                }
                ::rusty_lr::parser::table::IntermediateTables {
                    state_rows,
                    rules,
                }
                    .into()
            })
    }
}

// ==============================Generated Codes End===============================
        