
// This file was generated by rustylr 1.32.0
// This generated code is targeting rusty_lr version 4.1.0.
// There might be a build error if the version is not matched.
//
// ================================User Codes Begin================================

// =================================User Codes End=================================
/*
====================================Grammar=====================================

# of terminal classes: 31
# of states: 119

0: Json -> Element
1: Value -> Object
2: Value -> Array
3: Value -> String
4: Value -> Number
5: Value -> "true"
6: Value -> "false"
7: Value -> "null"
8: Object -> '{' WS '}'
9: Object -> '{' Members '}'
10: Object -> '{' error '}'
11: Members -> Member
12: Members -> Member ',' Members
13: Member -> WS String WS ':' Element
14: Array -> '[' $sep(Element, ',', *) ']'
15: Element -> WS Value WS
16: String -> '"' Character* '"'
17: Character -> '\\' Escape
18: Character -> [' '-'\u{10ffff}']-'"'-'\\'
19: Escape -> '"'
20: Escape -> '\\'
21: Escape -> '/'
22: Escape -> 'b'
23: Escape -> 'f'
24: Escape -> 'n'
25: Escape -> 'r'
26: Escape -> 't'
27: Escape -> 'u' Hex Hex Hex Hex
28: Hex -> ['0'-'9']
29: Hex -> ['A'-'F']
30: Hex -> ['a'-'f']
31: Number -> Integer ('.', Digits)? Exponent
32: Integer -> ['0'-'9']
33: Integer -> ['1'-'9'] Digit+
34: Integer -> '-' ['0'-'9']
35: Integer -> '-' ['1'-'9'] Digit+
36: Exponent -> ""
37: Exponent -> 'E' Sign Digit+
38: Exponent -> 'e' Sign Digit+
39: Sign -> ""
40: Sign -> '+'
41: Sign -> '-'
42: WS -> ""
43: WS -> ' ' WS
44: WS -> ['\t', '\n', '\r'] WS
45: "true" -> 't' 'r' 'u' 'e'
46: "false" -> 'f' 'a' 'l' 's' 'e'
47: "null" -> 'n' 'u' 'l' 'l'
48: $sep(Element, ',', +) -> Element
49: $sep(Element, ',', +) -> Element ',' $sep(Element, ',', +)
50: $sep(Element, ',', *) -> $sep(Element, ',', +)
51: $sep(Element, ',', *) -> 
52: Character+ -> Character
53: Character+ -> Character Character+
54: Character* -> Character+
55: Character* -> 
56: [' '-'\u{10ffff}']-'"'-'\\' -> ' '
57: [' '-'\u{10ffff}']-'"'-'\\' -> ['!', '#'-'*', ..., '~'-'\u{10ffff}']
58: [' '-'\u{10ffff}']-'"'-'\\' -> '+'
59: [' '-'\u{10ffff}']-'"'-'\\' -> ','
60: [' '-'\u{10ffff}']-'"'-'\\' -> '-'
61: [' '-'\u{10ffff}']-'"'-'\\' -> '.'
62: [' '-'\u{10ffff}']-'"'-'\\' -> '/'
63: [' '-'\u{10ffff}']-'"'-'\\' -> '0'
64: [' '-'\u{10ffff}']-'"'-'\\' -> ['1'-'9']
65: [' '-'\u{10ffff}']-'"'-'\\' -> ':'
66: [' '-'\u{10ffff}']-'"'-'\\' -> ['A'-'D', 'F']
67: [' '-'\u{10ffff}']-'"'-'\\' -> 'E'
68: [' '-'\u{10ffff}']-'"'-'\\' -> '['
69: [' '-'\u{10ffff}']-'"'-'\\' -> ']'
70: [' '-'\u{10ffff}']-'"'-'\\' -> 'a'
71: [' '-'\u{10ffff}']-'"'-'\\' -> 'b'
72: [' '-'\u{10ffff}']-'"'-'\\' -> ['c'-'d']
73: [' '-'\u{10ffff}']-'"'-'\\' -> 'e'
74: [' '-'\u{10ffff}']-'"'-'\\' -> 'f'
75: [' '-'\u{10ffff}']-'"'-'\\' -> 'l'
76: [' '-'\u{10ffff}']-'"'-'\\' -> 'n'
77: [' '-'\u{10ffff}']-'"'-'\\' -> 'r'
78: [' '-'\u{10ffff}']-'"'-'\\' -> 's'
79: [' '-'\u{10ffff}']-'"'-'\\' -> 't'
80: [' '-'\u{10ffff}']-'"'-'\\' -> 'u'
81: [' '-'\u{10ffff}']-'"'-'\\' -> '{'
82: [' '-'\u{10ffff}']-'"'-'\\' -> '}'
83: ['A'-'F'] -> ['A'-'D', 'F']
84: ['A'-'F'] -> 'E'
85: ['a'-'f'] -> 'a'
86: ['a'-'f'] -> 'b'
87: ['a'-'f'] -> ['c'-'d']
88: ['a'-'f'] -> 'e'
89: ['a'-'f'] -> 'f'
90: Digit+ -> ['0'-'9']
91: Digit+ -> ['0'-'9'] Digit+
92: ['0'-'9'] -> '0'
93: ['0'-'9'] -> ['1'-'9']
94: ('.', Digits) -> '.' Digit+
95: ('.', Digits)? -> ('.', Digits)
96: ('.', Digits)? -> 
97: "" -> 
98: Augmented -> Json eof

*/
// =============================Generated Codes Begin==============================
/// type alias for `Context`
#[allow(non_camel_case_types, dead_code)]
pub type JsonContext = ::rusty_lr::parser::deterministic::Context<
    JsonParser,
    JsonDataStack,
    u8,
>;
/// type alias for CFG production rule
#[allow(non_camel_case_types, dead_code)]
pub type JsonRule = ::rusty_lr::rule::ProductionRule<
    JsonTerminalClasses,
    JsonNonTerminals,
>;
/// type alias for runtime parser tables
#[allow(non_camel_case_types, dead_code)]
pub type JsonTables = ::rusty_lr::parser::table::DenseFlatTables<
    JsonTerminalClasses,
    JsonNonTerminals,
    u8,
    u8,
>;
/// type alias for `ParseError`
#[allow(non_camel_case_types, dead_code)]
pub type JsonParseError = ::rusty_lr::parser::deterministic::ParseError<
    char,
    std::ops::Range<usize>,
    ::rusty_lr::DefaultReduceActionError,
>;
/// A enum that represents terminal classes
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord
)]
#[repr(usize)]
pub enum JsonTerminalClasses {
    TermClass0,
    TermClass1,
    TermClass2,
    TermClass3,
    TermClass4,
    TermClass5,
    TermClass6,
    TermClass7,
    TermClass8,
    TermClass9,
    TermClass10,
    TermClass11,
    TermClass12,
    TermClass13,
    TermClass14,
    TermClass15,
    TermClass16,
    TermClass17,
    TermClass18,
    TermClass19,
    TermClass20,
    TermClass21,
    TermClass22,
    TermClass23,
    TermClass24,
    TermClass25,
    TermClass26,
    TermClass27,
    TermClass28,
    TermClass29,
    TermClass30,
    error,
    eof,
}
impl JsonTerminalClasses {
    #[inline]
    pub fn from_usize(value: usize) -> Self {
        debug_assert!(
            value < 33usize, "Terminal class index {} is out of bounds (max {})", value,
            33usize
        );
        unsafe { ::std::mem::transmute(value) }
    }
}
impl ::rusty_lr::parser::terminalclass::TerminalClass for JsonTerminalClasses {
    type Term = char;
    const ERROR: Self = Self::error;
    const EOF: Self = Self::eof;
    fn as_str(&self) -> &'static str {
        match self {
            JsonTerminalClasses::TermClass0 => "['\\t', '\\n', '\\r']",
            JsonTerminalClasses::TermClass1 => "' '",
            JsonTerminalClasses::TermClass2 => "<Others>",
            JsonTerminalClasses::TermClass3 => "['!', '#'-'*', ..., '~'-'\\u{10ffff}']",
            JsonTerminalClasses::TermClass4 => "'/'",
            JsonTerminalClasses::TermClass5 => "'b'",
            JsonTerminalClasses::TermClass6 => "'f'",
            JsonTerminalClasses::TermClass7 => "'n'",
            JsonTerminalClasses::TermClass8 => "'r'",
            JsonTerminalClasses::TermClass9 => "'t'",
            JsonTerminalClasses::TermClass10 => "'+'",
            JsonTerminalClasses::TermClass11 => "'-'",
            JsonTerminalClasses::TermClass12 => "','",
            JsonTerminalClasses::TermClass13 => "'.'",
            JsonTerminalClasses::TermClass14 => "'0'",
            JsonTerminalClasses::TermClass15 => "['1'-'9']",
            JsonTerminalClasses::TermClass16 => "':'",
            JsonTerminalClasses::TermClass17 => "['A'-'D', 'F']",
            JsonTerminalClasses::TermClass18 => "'E'",
            JsonTerminalClasses::TermClass19 => "'e'",
            JsonTerminalClasses::TermClass20 => "'['",
            JsonTerminalClasses::TermClass21 => "']'",
            JsonTerminalClasses::TermClass22 => "'a'",
            JsonTerminalClasses::TermClass23 => "['c'-'d']",
            JsonTerminalClasses::TermClass24 => "'l'",
            JsonTerminalClasses::TermClass25 => "'s'",
            JsonTerminalClasses::TermClass26 => "'u'",
            JsonTerminalClasses::TermClass27 => "'{'",
            JsonTerminalClasses::TermClass28 => "'}'",
            JsonTerminalClasses::TermClass29 => "'\"'",
            JsonTerminalClasses::TermClass30 => "'\\\\'",
            JsonTerminalClasses::error => "error",
            JsonTerminalClasses::eof => "eof",
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
    fn precedence(&self) -> ::rusty_lr::parser::Precedence {
        match self {
            JsonTerminalClasses::eof => {
                unreachable!("eof token cannot be used in precedence levels")
            }
            _ => ::rusty_lr::parser::Precedence::none(),
        }
    }
    fn from_term(terminal: &Self::Term) -> Self {
        #[allow(unreachable_patterns, unused_variables)]
        match terminal {
            '\t'..='\n' | '\r' => JsonTerminalClasses::TermClass0,
            ' ' => JsonTerminalClasses::TermClass1,
            '!'
            | '#'..='*'
            | ';'..='@'
            | 'G'..='Z'
            | '^'..='`'
            | 'g'..='k'
            | 'm'
            | 'o'..='q'
            | 'v'..='z'
            | '|'
            | '~'..='\u{10ffff}' => JsonTerminalClasses::TermClass3,
            '/' => JsonTerminalClasses::TermClass4,
            'b' => JsonTerminalClasses::TermClass5,
            'f' => JsonTerminalClasses::TermClass6,
            'n' => JsonTerminalClasses::TermClass7,
            'r' => JsonTerminalClasses::TermClass8,
            't' => JsonTerminalClasses::TermClass9,
            '+' => JsonTerminalClasses::TermClass10,
            '-' => JsonTerminalClasses::TermClass11,
            ',' => JsonTerminalClasses::TermClass12,
            '.' => JsonTerminalClasses::TermClass13,
            '0' => JsonTerminalClasses::TermClass14,
            '1'..='9' => JsonTerminalClasses::TermClass15,
            ':' => JsonTerminalClasses::TermClass16,
            'A'..='D' | 'F' => JsonTerminalClasses::TermClass17,
            'E' => JsonTerminalClasses::TermClass18,
            'e' => JsonTerminalClasses::TermClass19,
            '[' => JsonTerminalClasses::TermClass20,
            ']' => JsonTerminalClasses::TermClass21,
            'a' => JsonTerminalClasses::TermClass22,
            'c'..='d' => JsonTerminalClasses::TermClass23,
            'l' => JsonTerminalClasses::TermClass24,
            's' => JsonTerminalClasses::TermClass25,
            'u' => JsonTerminalClasses::TermClass26,
            '{' => JsonTerminalClasses::TermClass27,
            '}' => JsonTerminalClasses::TermClass28,
            '"' => JsonTerminalClasses::TermClass29,
            '\\' => JsonTerminalClasses::TermClass30,
            _ => JsonTerminalClasses::TermClass2,
        }
    }
}
impl std::fmt::Display for JsonTerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for JsonTerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
/// An enum that represents non-terminal symbols
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord
)]
#[repr(usize)]
pub enum JsonNonTerminals {
    Json,
    Value,
    Object,
    Members,
    Member,
    Array,
    Element,
    String,
    Character,
    Escape,
    Hex,
    Number,
    Integer,
    Exponent,
    Sign,
    WS,
    _LiteralString22,
    _LiteralString23,
    _LiteralString24,
    _ElementSepPlus25,
    _ElementSepStar26,
    _CharacterPlus27,
    _CharacterStar28,
    _TermSet29,
    _TermSet30,
    _TermSet31,
    _DigitPlus32,
    _TermSet33,
    _Group34,
    __Group34Question35,
    _LiteralString36,
    Augmented,
}
impl JsonNonTerminals {
    #[inline]
    pub fn from_usize(value: usize) -> Self {
        debug_assert!(
            value < 32usize, "Non-terminal index {} is out of bounds (max {})", value,
            32usize
        );
        unsafe { ::std::mem::transmute(value) }
    }
}
impl std::fmt::Display for JsonNonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for JsonNonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl ::rusty_lr::parser::nonterminal::NonTerminal for JsonNonTerminals {
    fn as_str(&self) -> &'static str {
        match self {
            JsonNonTerminals::Json => "Json",
            JsonNonTerminals::Value => "Value",
            JsonNonTerminals::Object => "Object",
            JsonNonTerminals::Members => "Members",
            JsonNonTerminals::Member => "Member",
            JsonNonTerminals::Array => "Array",
            JsonNonTerminals::Element => "Element",
            JsonNonTerminals::String => "String",
            JsonNonTerminals::Character => "Character",
            JsonNonTerminals::Escape => "Escape",
            JsonNonTerminals::Hex => "Hex",
            JsonNonTerminals::Number => "Number",
            JsonNonTerminals::Integer => "Integer",
            JsonNonTerminals::Exponent => "Exponent",
            JsonNonTerminals::Sign => "Sign",
            JsonNonTerminals::WS => "WS",
            JsonNonTerminals::_LiteralString22 => "\"true\"",
            JsonNonTerminals::_LiteralString23 => "\"false\"",
            JsonNonTerminals::_LiteralString24 => "\"null\"",
            JsonNonTerminals::_ElementSepPlus25 => "$sep(Element, ',', +)",
            JsonNonTerminals::_ElementSepStar26 => "$sep(Element, ',', *)",
            JsonNonTerminals::_CharacterPlus27 => "Character+",
            JsonNonTerminals::_CharacterStar28 => "Character*",
            JsonNonTerminals::_TermSet29 => "[' '-'\\u{10ffff}']-'\"'-'\\\\'",
            JsonNonTerminals::_TermSet30 => "['A'-'F']",
            JsonNonTerminals::_TermSet31 => "['a'-'f']",
            JsonNonTerminals::_DigitPlus32 => "Digit+",
            JsonNonTerminals::_TermSet33 => "['0'-'9']",
            JsonNonTerminals::_Group34 => "('.', Digits)",
            JsonNonTerminals::__Group34Question35 => "('.', Digits)?",
            JsonNonTerminals::_LiteralString36 => "\"\"",
            JsonNonTerminals::Augmented => "Augmented",
        }
    }
    fn nonterm_type(&self) -> Option<::rusty_lr::parser::nonterminal::NonTerminalType> {
        match self {
            JsonNonTerminals::Json => None,
            JsonNonTerminals::Value => None,
            JsonNonTerminals::Object => None,
            JsonNonTerminals::Members => None,
            JsonNonTerminals::Member => None,
            JsonNonTerminals::Array => None,
            JsonNonTerminals::Element => None,
            JsonNonTerminals::String => None,
            JsonNonTerminals::Character => None,
            JsonNonTerminals::Escape => None,
            JsonNonTerminals::Hex => None,
            JsonNonTerminals::Number => None,
            JsonNonTerminals::Integer => None,
            JsonNonTerminals::Exponent => None,
            JsonNonTerminals::Sign => None,
            JsonNonTerminals::WS => None,
            JsonNonTerminals::_LiteralString22 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::LiteralString)
            }
            JsonNonTerminals::_LiteralString23 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::LiteralString)
            }
            JsonNonTerminals::_LiteralString24 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::LiteralString)
            }
            JsonNonTerminals::_ElementSepPlus25 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusRight)
            }
            JsonNonTerminals::_ElementSepStar26 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Star)
            }
            JsonNonTerminals::_CharacterPlus27 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusRight)
            }
            JsonNonTerminals::_CharacterStar28 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Star)
            }
            JsonNonTerminals::_TermSet29 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::TerminalSet)
            }
            JsonNonTerminals::_TermSet30 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::TerminalSet)
            }
            JsonNonTerminals::_TermSet31 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::TerminalSet)
            }
            JsonNonTerminals::_DigitPlus32 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusRight)
            }
            JsonNonTerminals::_TermSet33 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::TerminalSet)
            }
            JsonNonTerminals::_Group34 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Group)
            }
            JsonNonTerminals::__Group34Question35 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Optional)
            }
            JsonNonTerminals::_LiteralString36 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::LiteralString)
            }
            JsonNonTerminals::Augmented => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Augmented)
            }
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub enum JsonData {
    Empty,
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub struct JsonDataStack {
    pub __stack: Vec<JsonData>,
}
impl Default for JsonDataStack {
    fn default() -> Self {
        Self { __stack: Vec::new() }
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut,
    dead_code
)]
impl JsonDataStack {
    ///Object -> '{' WS '}'
    #[inline]
    fn reduce_Object_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Object -> '{' Members '}'
    #[inline]
    fn reduce_Object_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Object -> '{' error '}'
    #[inline]
    fn reduce_Object_2(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.pop();
        let mut __rustylr_location_error = __location_stack.pop().unwrap();
        __location_stack.pop();
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        {
            data.push(__rustylr_location_error.clone());
        };
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Members -> Member
    #[inline]
    fn reduce_Members_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Members -> Member ',' Members
    #[inline]
    fn reduce_Members_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Member -> WS String WS ':' Element
    #[inline]
    fn reduce_Member_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                4usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 5);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 5);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Array -> '[' $sep(Element, ',', *) ']'
    #[inline]
    fn reduce_Array_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Element -> WS Value WS
    #[inline]
    fn reduce_Element_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///String -> '"' Character* '"'
    #[inline]
    fn reduce_String_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Character -> '\\' Escape
    #[inline]
    fn reduce_Character_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Escape -> 'u' Hex Hex Hex Hex
    #[inline]
    fn reduce_Escape_8(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                4usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 5);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 5);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Number -> Integer ('.', Digits)? Exponent
    #[inline]
    fn reduce_Number_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Integer -> ['1'-'9'] Digit+
    #[inline]
    fn reduce_Integer_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Integer -> '-' ['0'-'9']
    #[inline]
    fn reduce_Integer_2(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Integer -> '-' ['1'-'9'] Digit+
    #[inline]
    fn reduce_Integer_3(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Exponent -> 'E' Sign Digit+
    #[inline]
    fn reduce_Exponent_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Exponent -> 'e' Sign Digit+
    #[inline]
    fn reduce_Exponent_2(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///WS -> ' ' WS
    #[inline]
    fn reduce_WS_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///WS -> ['\t', '\n', '\r'] WS
    #[inline]
    fn reduce_WS_2(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///"true" -> 't' 'r' 'u' 'e'
    #[inline]
    fn reduce__LiteralString22_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 4);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 4);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///"false" -> 'f' 'a' 'l' 's' 'e'
    #[inline]
    fn reduce__LiteralString23_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                4usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 5);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 5);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///"null" -> 'n' 'u' 'l' 'l'
    #[inline]
    fn reduce__LiteralString24_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 4);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 4);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///$sep(Element, ',', +) -> Element
    #[inline]
    fn reduce__ElementSepPlus25_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///$sep(Element, ',', +) -> Element ',' $sep(Element, ',', +)
    #[inline]
    fn reduce__ElementSepPlus25_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 3);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///$sep(Element, ',', *) ->
    #[inline]
    fn reduce__ElementSepStar26_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Character+ -> Character
    #[inline]
    fn reduce__CharacterPlus27_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Character+ -> Character Character+
    #[inline]
    fn reduce__CharacterPlus27_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Character* ->
    #[inline]
    fn reduce__CharacterStar28_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Digit+ -> ['0'-'9']
    #[inline]
    fn reduce__DigitPlus32_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///Digit+ -> ['0'-'9'] Digit+
    #[inline]
    fn reduce__DigitPlus32_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///['0'-'9'] -> ['1'-'9']
    #[inline]
    fn reduce__TermSet33_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.pop();
        __data_stack.__stack.pop();
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///('.', Digits) -> '.' Digit+
    #[inline]
    fn reduce__Group34_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& JsonData::Empty))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& JsonData::Empty))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///('.', Digits)? ->
    #[inline]
    fn reduce___Group34Question35_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
    ///"" ->
    #[inline]
    fn reduce__LiteralString36_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<std::ops::Range<usize>>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<char>,
        data: &mut Vec<std::ops::Range<usize>>,
        __rustylr_location0: &mut std::ops::Range<usize>,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        __data_stack.__stack.push(JsonData::Empty);
        Ok(())
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    non_snake_case,
    non_camel_case_types,
    unused_variables
)]
impl ::rusty_lr::parser::data_stack::DataStack for JsonDataStack {
    type Term = char;
    type NonTerm = JsonNonTerminals;
    type ReduceActionError = ::rusty_lr::DefaultReduceActionError;
    type UserData = Vec<std::ops::Range<usize>>;
    type StartType = ();
    type Location = std::ops::Range<usize>;
    fn pop_start(&mut self) -> Option<Self::StartType> {
        self.__stack.pop();
        match self.__stack.pop() {
            Some(JsonData::Empty) => Some(()),
            _ => None,
        }
    }
    fn pop(&mut self) {
        self.__stack.pop();
    }
    fn push_terminal(&mut self, term: Self::Term) {
        self.__stack.push(JsonData::Empty);
    }
    fn push_empty(&mut self) {
        self.__stack.push(JsonData::Empty);
    }
    fn clear(&mut self) {
        self.__stack.clear();
    }
    fn reserve(&mut self, additional: usize) {
        self.__stack.reserve(additional);
    }
    fn split_off(&mut self, at: usize) -> Self {
        Self {
            __stack: self.__stack.split_off(at),
        }
    }
    fn truncate(&mut self, at: usize) {
        self.__stack.truncate(at);
    }
    fn append(&mut self, other: &mut Self) {
        self.__stack.append(&mut other.__stack);
    }
    fn reduce_action(
        data_stack: &mut Self,
        location_stack: &mut Vec<std::ops::Range<usize>>,
        push_data: bool,
        rule_index: usize,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Self::Term>,
        user_data: &mut Self::UserData,
        location0: &mut Self::Location,
    ) -> Result<(), Self::ReduceActionError> {
        match rule_index {
            8usize => {
                Self::reduce_Object_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            9usize => {
                Self::reduce_Object_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            10usize => {
                Self::reduce_Object_2(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            11usize => {
                Self::reduce_Members_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            12usize => {
                Self::reduce_Members_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            13usize => {
                Self::reduce_Member_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            14usize => {
                Self::reduce_Array_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            15usize => {
                Self::reduce_Element_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            16usize => {
                Self::reduce_String_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            17usize => {
                Self::reduce_Character_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            27usize => {
                Self::reduce_Escape_8(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            31usize => {
                Self::reduce_Number_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            33usize => {
                Self::reduce_Integer_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            34usize => {
                Self::reduce_Integer_2(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            35usize => {
                Self::reduce_Integer_3(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            37usize => {
                Self::reduce_Exponent_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            38usize => {
                Self::reduce_Exponent_2(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            43usize => {
                Self::reduce_WS_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            44usize => {
                Self::reduce_WS_2(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            45usize => {
                Self::reduce__LiteralString22_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            46usize => {
                Self::reduce__LiteralString23_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            47usize => {
                Self::reduce__LiteralString24_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            48usize => {
                Self::reduce__ElementSepPlus25_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            49usize => {
                Self::reduce__ElementSepPlus25_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            51usize => {
                Self::reduce__ElementSepStar26_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            52usize => {
                Self::reduce__CharacterPlus27_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            53usize => {
                Self::reduce__CharacterPlus27_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            55usize => {
                Self::reduce__CharacterStar28_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            90usize => {
                Self::reduce__DigitPlus32_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            91usize => {
                Self::reduce__DigitPlus32_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            93usize => {
                Self::reduce__TermSet33_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            94usize => {
                Self::reduce__Group34_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            96usize => {
                Self::reduce___Group34Question35_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            97usize => {
                Self::reduce__LiteralString36_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            _ => {
                unreachable!("Invalid Rule: {}", rule_index);
            }
        }
    }
}
/// A lightweight parser struct that references the static parser tables and production rules.
///
/// Since this struct only holds `'static` references to shared, read-only static parser tables,
/// it is extremely cheap to instantiate, copy, or clone, and takes very little space.
#[allow(unused_braces, unused_parens, unused_variables, non_snake_case, unused_mut)]
#[derive(Clone, Copy)]
pub struct JsonParser;
unsafe impl ::std::marker::Send for JsonParser {}
unsafe impl ::std::marker::Sync for JsonParser {}
#[rustfmt::skip]
impl ::rusty_lr::parser::Parser for JsonParser {
    type Term = char;
    type TermClass = JsonTerminalClasses;
    type NonTerm = JsonNonTerminals;
    type StateIndex = u8;
    type ReduceRules = u8;
    type Tables = JsonTables;
    const ERROR_USED: bool = true;
    fn precedence_types(level: u8) -> Option<::rusty_lr::rule::ReduceType> {
        #[allow(unreachable_patterns)]
        match level {
            _ => None,
        }
    }
    fn get_tables() -> &'static JsonTables {
        static TABLES: std::sync::OnceLock<JsonTables> = std::sync::OnceLock::new();
        TABLES
            .get_or_init(|| {
                static RULE_NAMES: &[u32] = &[
                    0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 8, 8, 9, 9, 9, 9,
                    9, 9, 9, 9, 9, 10, 10, 10, 11, 12, 12, 12, 12, 13, 13, 13, 14, 14,
                    14, 15, 15, 15, 16, 17, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23,
                    23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
                    23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 25, 25, 25, 25, 25, 26, 26,
                    27, 27, 28, 29, 29, 30, 31,
                ];
                static RULE_PRECEDENCES: &[u32] = &[
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0,
                ];
                static RULE_LENGTHS: &[u32] = &[
                    1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1, 3, 5, 3, 3, 3, 2, 1, 1, 1, 1, 1,
                    1, 1, 1, 1, 5, 1, 1, 1, 3, 1, 2, 2, 3, 1, 3, 3, 1, 1, 1, 1, 2, 2, 4,
                    5, 4, 1, 3, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
                    1, 1, 2, 1, 0, 0, 2,
                ];
                static SHIFT_TERM_DATA: &[u32] = &[
                    32768, 65537, 32768, 65537, 32768, 65537, 2147680288, 262150, 425991,
                    557065, 688139, 3604494, 884751, 950292, 1277979, 1703965, 294934,
                    327704, 360473, 393235, 458778, 491544, 524312, 589832, 622618,
                    655379, 851982, 720911, 786446, 786447, 786446, 786447, 786446,
                    786447, 32768, 65537, 1015820, 32768, 65537, 262150, 425991, 557065,
                    1081355, 3178510, 1179663, 950292, 1277979, 1703965, 851982, 1114127,
                    1146894, 1146895, 1146894, 1146895, 1146894, 1146895, 1245205,
                    1310720, 1343489, 2148859935, 1310720, 1343489, 1310720, 1343489,
                    1409052, 1474588, 1540108, 1572864, 1605633, 1572864, 1605633,
                    1572864, 1605633, 1703965, 1966081, 1966083, 1966084, 1966085,
                    1966086, 1966087, 1966088, 1966089, 1966090, 1966091, 1966092,
                    1966093, 1966094, 1966095, 1966096, 1966097, 1966098, 1966099,
                    1966100, 1966101, 1966102, 1966103, 1966104, 1966105, 1966106,
                    1966107, 1966108, 1736734, 1933316, 1933317, 1933318, 1933319,
                    1933320, 1933321, 1769498, 1933341, 1933342, 1802245, 1802246,
                    1802254, 1802255, 1802257, 1802258, 1802259, 1802262, 1802263,
                    1835013, 1835014, 1835022, 1835023, 1835025, 1835026, 1835027,
                    1835030, 1835031, 1867781, 1867782, 1867790, 1867791, 1867793,
                    1867794, 1867795, 1867798, 1867799, 1900549, 1900550, 1900558,
                    1900559, 1900561, 1900562, 1900563, 1900566, 1900567, 1966081,
                    1966083, 1966084, 1966085, 1966086, 1966087, 1966088, 1966089,
                    1966090, 1966091, 1966092, 1966093, 1966094, 1966095, 1966096,
                    1966097, 1966098, 1966099, 1966100, 1966101, 1966102, 1966103,
                    1966104, 1966105, 1966106, 1966107, 1966108, 1736734, 2064413,
                    2129920, 2162689, 2129920, 2162689, 2129920, 2162689, 2228240, 32768,
                    65537, 262150, 425991, 557065, 2326539, 2654222, 2424847, 950292,
                    1277979, 1703965, 851982, 2359311, 2392078, 2392079, 2392078,
                    2392079, 2392078, 2392079, 2490396, 1703965, 2555904, 2588673,
                    2555904, 2588673, 2555904, 2588673, 2686989, 2752526, 2752527,
                    2752526, 2752527, 2818066, 2949139, 2850826, 2850827, 2916366,
                    2916367, 2916366, 2916367, 2981898, 2981899, 2916366, 2916367,
                    3112960, 3145729, 3112960, 3145729, 3112960, 3145729, 3211277,
                    3244046, 3244047, 3244046, 3244047, 3309586, 3407891, 3342346,
                    3342347, 3375118, 3375119, 3375118, 3375119, 3440650, 3440651,
                    3375118, 3375119, 3538944, 3571713, 3538944, 3571713, 3538944,
                    3571713, 3637261, 3670030, 3670031, 3670030, 3670031, 3735570,
                    3833875, 3768330, 3768331, 3801102, 3801103, 3801102, 3801103,
                    3866634, 3866635, 3801102, 3801103,
                ];
                static SHIFT_TERM_OFFSETS: &[u32] = &[
                    0, 2, 4, 6, 6, 6, 7, 7, 16, 17, 18, 19, 20, 20, 21, 22, 23, 23, 24,
                    25, 26, 26, 28, 30, 30, 32, 32, 32, 34, 34, 36, 37, 39, 48, 50, 52,
                    54, 56, 57, 57, 60, 62, 64, 65, 65, 66, 66, 67, 69, 71, 73, 73, 74,
                    102, 111, 120, 129, 138, 147, 147, 147, 175, 175, 176, 176, 178, 180,
                    182, 183, 185, 185, 194, 196, 198, 200, 202, 204, 204, 206, 208, 210,
                    210, 211, 213, 213, 215, 217, 219, 221, 221, 223, 225, 227, 227, 227,
                    229, 231, 233, 234, 236, 238, 240, 242, 244, 246, 248, 250, 250, 252,
                    254, 256, 257, 259, 261, 263, 265, 267, 269, 271, 273,
                ];
                static SHIFT_NONTERM_DATA: &[u32] = &[
                    2147647488, 163846, 2147713039, 229406, 2147614735, 131102,
                    2147581967, 98334, 2150989825, 3506178, 3506181, 3506183, 3506187,
                    2151088140, 3506192, 3506193, 3506194, 3604507, 2148335643,
                    2148237338, 2148270107, 2148302874, 2148270107, 2148401178,
                    2148270107, 2148466694, 2148532239, 1212435, 2148696084, 1048606,
                    2148466694, 2148532239, 2150957075, 1048606, 2150563841, 3080194,
                    3080197, 3080199, 3080203, 2150662156, 3080208, 3080209, 3080210,
                    3178523, 2148335643, 2148237338, 2148630555, 2148302874, 2148630555,
                    2148401178, 2148630555, 2148925443, 2148990980, 2149941263, 2457630,
                    2147614735, 131102, 2147581967, 98334, 2149122051, 2148990980,
                    2149154831, 1671198, 2147614735, 131102, 2147581967, 98334,
                    2149580807, 2149449736, 2031637, 2149515286, 1966103, 2149416969,
                    2149285898, 1802264, 1802265, 1802267, 2149318666, 1835032, 1835033,
                    1835035, 2149351434, 1867800, 1867801, 1867803, 2149384202, 1900568,
                    1900569, 1900571, 2149449736, 2149482517, 1966103, 2149679119,
                    2195486, 2147614735, 131102, 2147581967, 98334, 2149744646,
                    2149777423, 2293790, 2150006785, 2523138, 2523141, 2523143, 2523147,
                    2150137868, 2523152, 2523153, 2523154, 2654235, 2148335643,
                    2148237338, 2149875739, 2148302874, 2149875739, 2148401178,
                    2149875739, 2149580807, 2150105103, 2621470, 2147614735, 131102,
                    2147581967, 98334, 2785308, 2150268957, 2150203418, 2150236187,
                    2148302874, 2150236187, 2150531085, 3047454, 2150334478, 2850846,
                    2150367258, 2150400027, 2148302874, 2150400027, 2150465550, 2981918,
                    2150498330, 2150400027, 2150105103, 2621470, 2147614735, 131102,
                    2147581967, 98334, 3276828, 2150760477, 2150203418, 2150727707,
                    2148302874, 2150727707, 2150531085, 3047454, 2150825998, 3342366,
                    2150367258, 2150858779, 2148302874, 2150858779, 2150924302, 3440670,
                    2150498330, 2150858779, 2150105103, 2621470, 2147614735, 131102,
                    2147581967, 98334, 3702812, 2151186461, 2150203418, 2151153691,
                    2148302874, 2151153691, 2150531085, 3047454, 2151251982, 3768350,
                    2150367258, 2151284763, 2148302874, 2151284763, 2151350286, 3866654,
                    2150498330, 2151284763,
                ];
                static SHIFT_NONTERM_OFFSETS: &[u32] = &[
                    0, 4, 6, 8, 8, 8, 8, 8, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
                    18, 18, 18, 19, 21, 21, 23, 23, 23, 25, 25, 30, 30, 34, 44, 45, 47,
                    49, 51, 51, 51, 55, 57, 59, 59, 59, 59, 59, 59, 63, 65, 67, 67, 68,
                    72, 73, 77, 81, 85, 89, 89, 89, 92, 92, 92, 92, 94, 96, 98, 98, 101,
                    101, 111, 112, 114, 116, 118, 119, 119, 121, 123, 125, 125, 127, 129,
                    129, 131, 133, 135, 137, 137, 139, 141, 143, 143, 143, 145, 147, 149,
                    151, 153, 155, 157, 159, 161, 163, 165, 167, 167, 169, 171, 173, 175,
                    177, 179, 181, 183, 185, 187, 189, 191,
                ];
                static REDUCE_DATA: &[u32] = &[
                    6, 1, 97, 7, 1, 97, 9, 1, 97, 11, 1, 97, 14, 1, 97, 15, 1, 97, 20, 1,
                    97, 27, 1, 97, 29, 1, 97, 6, 1, 97, 7, 1, 97, 9, 1, 97, 11, 1, 97,
                    14, 1, 97, 15, 1, 97, 20, 1, 97, 27, 1, 97, 29, 1, 97, 6, 1, 97, 7,
                    1, 97, 9, 1, 97, 11, 1, 97, 14, 1, 97, 15, 1, 97, 20, 1, 97, 27, 1,
                    97, 29, 1, 97, 6, 1, 43, 7, 1, 43, 9, 1, 43, 11, 1, 43, 12, 1, 43,
                    14, 1, 43, 15, 1, 43, 16, 1, 43, 20, 1, 43, 21, 1, 43, 27, 1, 43, 28,
                    1, 43, 29, 1, 43, 32, 1, 43, 6, 1, 44, 7, 1, 44, 9, 1, 44, 11, 1, 44,
                    12, 1, 44, 14, 1, 44, 15, 1, 44, 16, 1, 44, 20, 1, 44, 21, 1, 44, 27,
                    1, 44, 28, 1, 44, 29, 1, 44, 32, 1, 44, 0, 1, 46, 1, 1, 46, 12, 1,
                    46, 21, 1, 46, 28, 1, 46, 32, 1, 46, 0, 1, 47, 1, 1, 47, 12, 1, 47,
                    21, 1, 47, 28, 1, 47, 32, 1, 47, 0, 1, 45, 1, 1, 45, 12, 1, 45, 21,
                    1, 45, 28, 1, 45, 32, 1, 45, 0, 1, 93, 1, 1, 93, 13, 1, 93, 18, 1,
                    93, 19, 1, 93, 32, 1, 93, 0, 1, 35, 1, 1, 35, 12, 1, 35, 13, 1, 35,
                    18, 1, 35, 19, 1, 35, 21, 1, 35, 28, 1, 35, 32, 1, 35, 0, 1, 90, 1,
                    1, 90, 13, 1, 90, 18, 1, 90, 19, 1, 90, 32, 1, 90, 0, 1, 91, 1, 1,
                    91, 12, 1, 91, 13, 1, 91, 18, 1, 91, 19, 1, 91, 21, 1, 91, 28, 1, 91,
                    32, 1, 91, 0, 1, 34, 1, 1, 34, 12, 1, 34, 13, 1, 34, 18, 1, 34, 19,
                    1, 34, 21, 1, 34, 28, 1, 34, 32, 1, 34, 0, 1, 93, 1, 1, 93, 13, 1,
                    93, 18, 1, 93, 19, 1, 93, 32, 1, 93, 0, 1, 33, 1, 1, 33, 12, 1, 33,
                    13, 1, 33, 18, 1, 33, 19, 1, 33, 21, 1, 33, 28, 1, 33, 32, 1, 33, 6,
                    1, 97, 7, 1, 97, 9, 1, 97, 11, 1, 97, 14, 1, 97, 15, 1, 97, 20, 1,
                    97, 21, 1, 51, 27, 1, 97, 29, 1, 97, 21, 1, 48, 6, 1, 97, 7, 1, 97,
                    9, 1, 97, 11, 1, 97, 14, 1, 97, 15, 1, 97, 20, 1, 97, 27, 1, 97, 29,
                    1, 97, 0, 1, 93, 1, 1, 93, 12, 1, 93, 13, 1, 93, 18, 1, 93, 19, 1,
                    93, 21, 1, 93, 0, 1, 90, 1, 1, 90, 12, 1, 90, 13, 1, 90, 18, 1, 90,
                    19, 1, 90, 21, 1, 90, 0, 1, 93, 1, 1, 93, 12, 1, 93, 13, 1, 93, 18,
                    1, 93, 19, 1, 93, 21, 1, 93, 0, 1, 14, 1, 1, 14, 12, 1, 14, 21, 1,
                    14, 28, 1, 14, 32, 1, 14, 28, 1, 97, 29, 1, 97, 28, 1, 97, 29, 1, 97,
                    28, 1, 97, 29, 1, 97, 0, 1, 10, 1, 1, 10, 12, 1, 10, 21, 1, 10, 28,
                    1, 10, 32, 1, 10, 0, 1, 9, 1, 1, 9, 12, 1, 9, 21, 1, 9, 28, 1, 9, 32,
                    1, 9, 28, 1, 11, 29, 1, 97, 29, 1, 97, 29, 1, 97, 28, 1, 12, 29, 1,
                    55, 1, 1, 27, 3, 1, 27, 4, 1, 27, 5, 1, 27, 6, 1, 27, 7, 1, 27, 8, 1,
                    27, 9, 1, 27, 10, 1, 27, 11, 1, 27, 12, 1, 27, 13, 1, 27, 14, 1, 27,
                    15, 1, 27, 16, 1, 27, 17, 1, 27, 18, 1, 27, 19, 1, 27, 20, 1, 27, 21,
                    1, 27, 22, 1, 27, 23, 1, 27, 24, 1, 27, 25, 1, 27, 26, 1, 27, 27, 1,
                    27, 28, 1, 27, 29, 1, 27, 30, 1, 27, 1, 1, 17, 3, 1, 17, 4, 1, 17, 5,
                    1, 17, 6, 1, 17, 7, 1, 17, 8, 1, 17, 9, 1, 17, 10, 1, 17, 11, 1, 17,
                    12, 1, 17, 13, 1, 17, 14, 1, 17, 15, 1, 17, 16, 1, 17, 17, 1, 17, 18,
                    1, 17, 19, 1, 17, 20, 1, 17, 21, 1, 17, 22, 1, 17, 23, 1, 17, 24, 1,
                    17, 25, 1, 17, 26, 1, 17, 27, 1, 17, 28, 1, 17, 29, 1, 17, 30, 1, 17,
                    29, 1, 52, 29, 1, 53, 0, 1, 16, 1, 1, 16, 12, 1, 16, 16, 1, 16, 21,
                    1, 16, 28, 1, 16, 32, 1, 16, 16, 1, 97, 16, 1, 97, 16, 1, 97, 6, 1,
                    97, 7, 1, 97, 9, 1, 97, 11, 1, 97, 14, 1, 97, 15, 1, 97, 20, 1, 97,
                    27, 1, 97, 29, 1, 97, 12, 1, 13, 28, 1, 13, 0, 1, 93, 1, 1, 93, 12,
                    1, 93, 13, 1, 93, 18, 1, 93, 19, 1, 93, 28, 1, 93, 0, 1, 90, 1, 1,
                    90, 12, 1, 90, 13, 1, 90, 18, 1, 90, 19, 1, 90, 28, 1, 90, 0, 1, 93,
                    1, 1, 93, 12, 1, 93, 13, 1, 93, 18, 1, 93, 19, 1, 93, 28, 1, 93, 0,
                    1, 8, 1, 1, 8, 12, 1, 8, 21, 1, 8, 28, 1, 8, 32, 1, 8, 12, 1, 97, 28,
                    1, 97, 12, 1, 97, 28, 1, 97, 12, 1, 97, 28, 1, 97, 12, 1, 15, 21, 1,
                    15, 28, 1, 15, 32, 1, 15, 0, 1, 96, 1, 1, 96, 12, 1, 96, 18, 1, 96,
                    19, 1, 96, 28, 1, 96, 0, 1, 94, 1, 1, 94, 12, 1, 94, 18, 1, 94, 19,
                    1, 94, 21, 1, 94, 28, 1, 94, 32, 1, 94, 0, 1, 90, 1, 1, 90, 12, 1,
                    90, 18, 1, 90, 19, 1, 90, 28, 1, 90, 0, 1, 97, 1, 1, 97, 12, 1, 97,
                    28, 1, 97, 14, 1, 97, 15, 1, 97, 0, 1, 37, 1, 1, 37, 12, 1, 37, 21,
                    1, 37, 28, 1, 37, 32, 1, 37, 0, 1, 90, 1, 1, 90, 12, 1, 90, 28, 1,
                    90, 14, 1, 97, 15, 1, 97, 0, 1, 38, 1, 1, 38, 12, 1, 38, 21, 1, 38,
                    28, 1, 38, 32, 1, 38, 0, 1, 31, 1, 1, 31, 12, 1, 31, 21, 1, 31, 28,
                    1, 31, 32, 1, 31, 12, 1, 97, 21, 1, 97, 12, 1, 97, 21, 1, 97, 12, 1,
                    97, 21, 1, 97, 0, 1, 96, 1, 1, 96, 12, 1, 96, 18, 1, 96, 19, 1, 96,
                    21, 1, 96, 0, 1, 90, 1, 1, 90, 12, 1, 90, 18, 1, 90, 19, 1, 90, 21,
                    1, 90, 0, 1, 97, 1, 1, 97, 12, 1, 97, 21, 1, 97, 14, 1, 97, 15, 1,
                    97, 0, 1, 90, 1, 1, 90, 12, 1, 90, 21, 1, 90, 14, 1, 97, 15, 1, 97,
                    21, 1, 49, 32, 1, 97, 32, 1, 97, 32, 1, 97, 0, 1, 96, 1, 1, 96, 18,
                    1, 96, 19, 1, 96, 32, 1, 96, 0, 1, 90, 1, 1, 90, 18, 1, 90, 19, 1,
                    90, 32, 1, 90, 0, 1, 97, 1, 1, 97, 32, 1, 97, 14, 1, 97, 15, 1, 97,
                    0, 1, 90, 1, 1, 90, 32, 1, 90, 14, 1, 97, 15, 1, 97,
                ];
                static REDUCE_OFFSETS: &[u32] = &[
                    0, 27, 54, 81, 123, 165, 165, 165, 165, 165, 165, 165, 165, 183, 183,
                    183, 183, 201, 201, 201, 201, 219, 219, 237, 264, 282, 309, 336, 354,
                    381, 411, 414, 441, 441, 441, 462, 483, 504, 504, 522, 528, 534, 540,
                    540, 558, 558, 576, 579, 582, 585, 588, 591, 591, 594, 594, 594, 594,
                    594, 594, 681, 768, 771, 774, 774, 795, 798, 801, 804, 804, 831, 837,
                    837, 837, 858, 879, 900, 900, 918, 924, 930, 936, 948, 966, 966, 990,
                    1008, 1020, 1026, 1026, 1044, 1056, 1062, 1062, 1080, 1098, 1104,
                    1110, 1116, 1134, 1134, 1152, 1164, 1170, 1170, 1182, 1188, 1188,
                    1191, 1194, 1197, 1200, 1215, 1215, 1230, 1239, 1245, 1245, 1254,
                    1260, 1260,
                ];
                static CAN_ACCEPT_ERROR: &[u8] = &[
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0,
                ];
                let num_rules = 99usize;
                let mut rules = Vec::with_capacity(num_rules);
                for i in 0..num_rules {
                    let name = JsonNonTerminals::from_usize(RULE_NAMES[i] as usize);
                    let prec_val = RULE_PRECEDENCES[i];
                    let precedence = match prec_val & 3 {
                        0 => ::rusty_lr::rule::Precedence::None,
                        1 => {
                            ::rusty_lr::rule::Precedence::Fixed((prec_val >> 2) as usize)
                        }
                        2 => {
                            ::rusty_lr::rule::Precedence::Dynamic(
                                (prec_val >> 2) as usize,
                            )
                        }
                        _ => unreachable!(),
                    };
                    rules
                        .push(::rusty_lr::parser::table::RuleInfo {
                            name,
                            len: RULE_LENGTHS[i] as usize,
                            precedence,
                        });
                }
                let num_states = 119usize;
                let mut state_rows = Vec::with_capacity(num_states);
                for i in 0..num_states {
                    let term_start = SHIFT_TERM_OFFSETS[i] as usize;
                    let term_end = SHIFT_TERM_OFFSETS[i + 1] as usize;
                    let mut shift_goto_map_term = Vec::with_capacity(
                        term_end - term_start,
                    );
                    for idx in term_start..term_end {
                        let val = SHIFT_TERM_DATA[idx];
                        let term_class = JsonTerminalClasses::from_usize(
                            (val & 0x7fff) as usize,
                        );
                        let state = ((val >> 15) & 0xffff) as u8;
                        let push = (val >> 31) != 0;
                        shift_goto_map_term
                            .push((
                                term_class,
                                ::rusty_lr::parser::table::ShiftTarget::new(state, push),
                            ));
                    }
                    let nonterm_start = SHIFT_NONTERM_OFFSETS[i] as usize;
                    let nonterm_end = SHIFT_NONTERM_OFFSETS[i + 1] as usize;
                    let mut shift_goto_map_nonterm = Vec::with_capacity(
                        nonterm_end - nonterm_start,
                    );
                    for idx in nonterm_start..nonterm_end {
                        let val = SHIFT_NONTERM_DATA[idx];
                        let nonterm = JsonNonTerminals::from_usize(
                            (val & 0x7fff) as usize,
                        );
                        let state = ((val >> 15) & 0xffff) as u8;
                        let push = (val >> 31) != 0;
                        shift_goto_map_nonterm
                            .push((
                                nonterm,
                                ::rusty_lr::parser::table::ShiftTarget::new(state, push),
                            ));
                    }
                    let reduce_start = REDUCE_OFFSETS[i] as usize;
                    let reduce_end = REDUCE_OFFSETS[i + 1] as usize;
                    let mut reduce_map = Vec::new();
                    let mut idx = reduce_start;
                    while idx < reduce_end {
                        let term_val = REDUCE_DATA[idx];
                        let term_class = JsonTerminalClasses::from_usize(
                            term_val as usize,
                        );
                        let len = REDUCE_DATA[idx + 1] as usize;
                        let mut rules = Vec::with_capacity(len);
                        for r_idx in 0..len {
                            rules.push(REDUCE_DATA[idx + 2 + r_idx] as u8);
                        }
                        reduce_map.push((term_class, rules));
                        idx += 2 + len;
                    }
                    let can_accept_error = match CAN_ACCEPT_ERROR[i] {
                        0 => ::rusty_lr::TriState::False,
                        1 => ::rusty_lr::TriState::True,
                        2 => ::rusty_lr::TriState::Maybe,
                        _ => unreachable!(),
                    };
                    let intermediate = ::rusty_lr::parser::state::IntermediateState {
                        shift_goto_map_term,
                        shift_goto_map_nonterm,
                        reduce_map,
                        ruleset: Vec::new(),
                        can_accept_error,
                    };
                    state_rows.push(intermediate);
                }
                ::rusty_lr::parser::table::IntermediateTables {
                    state_rows,
                    rules,
                }
                    .into()
            })
    }
}

// ==============================Generated Codes End===============================
        