[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_lr = { path = "../../rusty_lr" }


[build-dependencies]
rusty_lr = { path = "../../rusty_lr", features = ["build"] }
