[package]
name = "calculator_u8"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_lr = { path = "../../rusty_lr", features = ["tree"] }


[build-dependencies]
rusty_lr = { path = "../../rusty_lr", features = ["build"] }
