[package]
name = "rustylr"
version = "0.14.2"
edition = "2021"
license = "MIT"
description = "executable for rusty_lr"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "bison", "lr", "glr", "compiler"]
categories = ["parsing"]

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
rusty_lr_buildscript = "0.12.0"
# rusty_lr_buildscript = { path = "../rusty_lr_buildscript" }
