[package]
name = "rustylr"
version = "0.6.1"
edition = "2021"
license = "MIT"
description = "LR(1), LALR(1) parser code generation with rusty_lr"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[dependencies]
proc-macro2 = { version = "1.0.86", features = ["span-locations"] }
quote = "1.0"
clap = { version = "4.5.7", features = ["derive"] }
# rusty_lr_parser = { path = "../rusty_lr_parser" }
rusty_lr_parser = "3.1"
# rusty_lr_core = { path = "../rusty_lr_core", features = ["fxhash"] }
rusty_lr_core = { version = "1.4", features = ["fxhash"] }
codespan-reporting = "0.11"
