[package]
name = "rustylr"
version = "1.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "executable for rusty_lr"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "bison", "lr", "glr", "compiler"]
categories = ["parsing"]

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
rusty_lr_buildscript = { version = "0.34.0", path = "../rusty_lr_buildscript", features = [
  "fxhash",
] }
