[package]
name = "rustylr"
version = "1.19.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Executable for rusty_lr, a parser generator that converts context-free grammars into IELR(1)/LALR(1) tables with deterministic LR and non-deterministic GLR parsing support"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "bison", "lr", "glr", "compiler"]
categories = ["parsing"]

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
rusty_lr_buildscript = { version = "0.53.0", path = "../rusty_lr_buildscript" }
