// This file was generated by rustylr 0.16.0
//
// Input file: ../rusty_lr_parser/src/parser/parser.rs
// Output file: parser_expanded.rs
// ================================User Codes Begin================================
use crate::parser::args::GrammarArgs;
use crate::parser::args::PatternArgs;
use crate::parser::args::RuleDefArgs;
use crate::parser::args::RuleLineArgs;
use crate::parser::args::TerminalSetOrIdent;
use crate::parser::lexer::Lexed;
use crate::terminalset::TerminalSet;
use crate::terminalset::TerminalSetItem;
use proc_macro2::Group;
use proc_macro2::Ident;
use proc_macro2::Punct;
use proc_macro2::Spacing;
use proc_macro2::Span;
use proc_macro2::TokenStream;
use quote::ToTokens;
use rusty_lr_core::ReduceType;
use std::boxed::Box;
macro_rules ! punct (($ l : literal) => { Punct :: new ($ l , Spacing :: Alone) } ;) ;
// =================================User Codes End=================================
/*
====================================Grammar=====================================
Rule -> ident RuleType colon RuleLines semicolon
RuleType -> parengroup
RuleType ->
RuleLines -> RuleLines pipe RuleLine
RuleLines -> RuleLine
RuleLine -> TokenMapped* Action
TokenMapped -> Pattern
TokenMapped -> ident equal Pattern
TerminalSetItem -> ident
TerminalSetItem -> ident minus ident
TerminalSet -> lbracket caret? TerminalSetItem* rbracket
Pattern -> ident
Pattern -> Pattern plus
Pattern -> Pattern star
Pattern -> Pattern question
Pattern -> Pattern exclamation
Pattern -> TerminalSet
Pattern -> Pattern slash TerminalSetOrIdent
Pattern -> lparen Pattern+ rparen
Action -> bracegroup
Action ->
TokenDef -> token ident RustCode semicolon
RustCode -> [^semicolon, lparen-glr]+
StartDef -> start ident semicolon
EofDef -> eofdef RustCode semicolon
TokenTypeDef -> tokentype RustCode semicolon
UserDataDef -> userdata RustCode semicolon
TerminalSetOrIdent -> TerminalSet
TerminalSetOrIdent -> ident
ReduceType -> left
ReduceType -> right
ReduceDef -> ReduceType TerminalSetOrIdent semicolon
ErrorDef -> errortype RustCode semicolon
ModulePrefixDef -> moduleprefix RustCode semicolon
Glr -> glr semicolon
GrammarLine -> Rule
GrammarLine -> TokenDef
GrammarLine -> StartDef
GrammarLine -> EofDef
GrammarLine -> TokenTypeDef
GrammarLine -> UserDataDef
GrammarLine -> ReduceDef
GrammarLine -> ErrorDef
GrammarLine -> ModulePrefixDef
GrammarLine -> Glr
Grammar -> GrammarLine+
TokenMapped+ -> TokenMapped
TokenMapped+ -> TokenMapped+ TokenMapped
TokenMapped* -> TokenMapped+
TokenMapped* ->
caret? -> caret
caret? ->
TerminalSetItem+ -> TerminalSetItem
TerminalSetItem+ -> TerminalSetItem+ TerminalSetItem
TerminalSetItem* -> TerminalSetItem+
TerminalSetItem* ->
Pattern+ -> Pattern
Pattern+ -> Pattern+ Pattern
[^semicolon, lparen-glr] -> ident
[^semicolon, lparen-glr] -> colon
[^semicolon, lparen-glr] -> pipe
[^semicolon, lparen-glr] -> percent
[^semicolon, lparen-glr] -> equal
[^semicolon, lparen-glr] -> plus
[^semicolon, lparen-glr] -> star
[^semicolon, lparen-glr] -> question
[^semicolon, lparen-glr] -> caret
[^semicolon, lparen-glr] -> minus
[^semicolon, lparen-glr] -> exclamation
[^semicolon, lparen-glr] -> slash
[^semicolon, lparen-glr] -> otherpunct
[^semicolon, lparen-glr] -> literal
[^semicolon, lparen-glr] -> parengroup
[^semicolon, lparen-glr] -> bracegroup
[^semicolon, lparen-glr] -> bracketgroup
[^semicolon, lparen-glr] -> nonegroup
[^semicolon, lparen-glr]+ -> [^semicolon, lparen-glr]
[^semicolon, lparen-glr]+ -> [^semicolon, lparen-glr]+ [^semicolon, lparen-glr]
GrammarLine+ -> GrammarLine
GrammarLine+ -> GrammarLine GrammarLine+
Augmented -> Grammar eof

*/
// =============================Generated Codes Begin==============================
#[doc = r" type alias for `Context`"]
#[allow(non_camel_case_types, dead_code)]
pub type GrammarContext = ::rusty_lr_core::lr::Context<GrammarStack>;
#[doc = r" type alias for CFG production rule"]
#[allow(non_camel_case_types, dead_code)]
pub type GrammarRule = ::rusty_lr_core::ProductionRule<Lexed, GrammarNonTerminals>;
#[doc = r" type alias for DFA state"]
#[allow(non_camel_case_types, dead_code)]
pub type GrammarState = ::rusty_lr_core::lr::State<Lexed, GrammarNonTerminals>;
#[doc = r" type alias for `ParseError`"]
#[allow(non_camel_case_types, dead_code)]
pub type GrammarParseError =
    ::rusty_lr_core::lr::ParseError<Lexed, ::rusty_lr_core::DefaultReduceActionError>;
#[doc = r" type alias for `InvalidTerminalError`"]
#[allow(non_camel_case_types, dead_code)]
pub type GrammarInvalidTerminalError = ::rusty_lr_core::lr::InvalidTerminalError<Lexed>;
#[doc = r" An enum that represents non-terminal symbols"]
#[allow(non_camel_case_types)]
#[derive(
    Clone,
    Copy,
    std :: hash :: Hash,
    std :: cmp :: PartialEq,
    std :: cmp :: Eq,
    std :: cmp :: PartialOrd,
    std :: cmp :: Ord,
)]
pub enum GrammarNonTerminals {
    Rule,
    RuleType,
    RuleLines,
    RuleLine,
    TokenMapped,
    TerminalSetItem,
    TerminalSet,
    Pattern,
    Action,
    TokenDef,
    RustCode,
    StartDef,
    EofDef,
    TokenTypeDef,
    UserDataDef,
    TerminalSetOrIdent,
    ReduceType,
    ReduceDef,
    ErrorDef,
    ModulePrefixDef,
    Glr,
    GrammarLine,
    Grammar,
    _TokenMapped_Plus23,
    _TokenMapped_Star24,
    _caret_Question25,
    _TerminalSetItem_Plus26,
    _TerminalSetItem_Star27,
    _Pattern_Plus28,
    _TerminalSet29,
    __TerminalSet29_Plus30,
    _GrammarLine_Plus31,
    Augmented,
}
impl std::fmt::Display for GrammarNonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GrammarNonTerminals::Rule => write!(f, "Rule"),
            GrammarNonTerminals::RuleType => write!(f, "RuleType"),
            GrammarNonTerminals::RuleLines => write!(f, "RuleLines"),
            GrammarNonTerminals::RuleLine => write!(f, "RuleLine"),
            GrammarNonTerminals::TokenMapped => write!(f, "TokenMapped"),
            GrammarNonTerminals::TerminalSetItem => write!(f, "TerminalSetItem"),
            GrammarNonTerminals::TerminalSet => write!(f, "TerminalSet"),
            GrammarNonTerminals::Pattern => write!(f, "Pattern"),
            GrammarNonTerminals::Action => write!(f, "Action"),
            GrammarNonTerminals::TokenDef => write!(f, "TokenDef"),
            GrammarNonTerminals::RustCode => write!(f, "RustCode"),
            GrammarNonTerminals::StartDef => write!(f, "StartDef"),
            GrammarNonTerminals::EofDef => write!(f, "EofDef"),
            GrammarNonTerminals::TokenTypeDef => write!(f, "TokenTypeDef"),
            GrammarNonTerminals::UserDataDef => write!(f, "UserDataDef"),
            GrammarNonTerminals::TerminalSetOrIdent => write!(f, "TerminalSetOrIdent"),
            GrammarNonTerminals::ReduceType => write!(f, "ReduceType"),
            GrammarNonTerminals::ReduceDef => write!(f, "ReduceDef"),
            GrammarNonTerminals::ErrorDef => write!(f, "ErrorDef"),
            GrammarNonTerminals::ModulePrefixDef => write!(f, "ModulePrefixDef"),
            GrammarNonTerminals::Glr => write!(f, "Glr"),
            GrammarNonTerminals::GrammarLine => write!(f, "GrammarLine"),
            GrammarNonTerminals::Grammar => write!(f, "Grammar"),
            GrammarNonTerminals::_TokenMapped_Plus23 => write!(f, "TokenMapped+"),
            GrammarNonTerminals::_TokenMapped_Star24 => write!(f, "TokenMapped*"),
            GrammarNonTerminals::_caret_Question25 => write!(f, "caret?"),
            GrammarNonTerminals::_TerminalSetItem_Plus26 => write!(f, "TerminalSetItem+"),
            GrammarNonTerminals::_TerminalSetItem_Star27 => write!(f, "TerminalSetItem*"),
            GrammarNonTerminals::_Pattern_Plus28 => write!(f, "Pattern+"),
            GrammarNonTerminals::_TerminalSet29 => write!(f, "[^semicolon, lparen-glr]"),
            GrammarNonTerminals::__TerminalSet29_Plus30 => write!(f, "[^semicolon, lparen-glr]+"),
            GrammarNonTerminals::_GrammarLine_Plus31 => write!(f, "GrammarLine+"),
            GrammarNonTerminals::Augmented => write!(f, "Augmented"),
        }
    }
}
impl std::fmt::Debug for GrammarNonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GrammarNonTerminals::Rule => write!(f, "Rule"),
            GrammarNonTerminals::RuleType => write!(f, "RuleType"),
            GrammarNonTerminals::RuleLines => write!(f, "RuleLines"),
            GrammarNonTerminals::RuleLine => write!(f, "RuleLine"),
            GrammarNonTerminals::TokenMapped => write!(f, "TokenMapped"),
            GrammarNonTerminals::TerminalSetItem => write!(f, "TerminalSetItem"),
            GrammarNonTerminals::TerminalSet => write!(f, "TerminalSet"),
            GrammarNonTerminals::Pattern => write!(f, "Pattern"),
            GrammarNonTerminals::Action => write!(f, "Action"),
            GrammarNonTerminals::TokenDef => write!(f, "TokenDef"),
            GrammarNonTerminals::RustCode => write!(f, "RustCode"),
            GrammarNonTerminals::StartDef => write!(f, "StartDef"),
            GrammarNonTerminals::EofDef => write!(f, "EofDef"),
            GrammarNonTerminals::TokenTypeDef => write!(f, "TokenTypeDef"),
            GrammarNonTerminals::UserDataDef => write!(f, "UserDataDef"),
            GrammarNonTerminals::TerminalSetOrIdent => write!(f, "TerminalSetOrIdent"),
            GrammarNonTerminals::ReduceType => write!(f, "ReduceType"),
            GrammarNonTerminals::ReduceDef => write!(f, "ReduceDef"),
            GrammarNonTerminals::ErrorDef => write!(f, "ErrorDef"),
            GrammarNonTerminals::ModulePrefixDef => write!(f, "ModulePrefixDef"),
            GrammarNonTerminals::Glr => write!(f, "Glr"),
            GrammarNonTerminals::GrammarLine => write!(f, "GrammarLine"),
            GrammarNonTerminals::Grammar => write!(f, "Grammar"),
            GrammarNonTerminals::_TokenMapped_Plus23 => write!(f, "TokenMapped+"),
            GrammarNonTerminals::_TokenMapped_Star24 => write!(f, "TokenMapped*"),
            GrammarNonTerminals::_caret_Question25 => write!(f, "caret?"),
            GrammarNonTerminals::_TerminalSetItem_Plus26 => write!(f, "TerminalSetItem+"),
            GrammarNonTerminals::_TerminalSetItem_Star27 => write!(f, "TerminalSetItem*"),
            GrammarNonTerminals::_Pattern_Plus28 => write!(f, "Pattern+"),
            GrammarNonTerminals::_TerminalSet29 => write!(f, "[^semicolon, lparen-glr]"),
            GrammarNonTerminals::__TerminalSet29_Plus30 => write!(f, "[^semicolon, lparen-glr]+"),
            GrammarNonTerminals::_GrammarLine_Plus31 => write!(f, "GrammarLine+"),
            GrammarNonTerminals::Augmented => write!(f, "Augmented"),
        }
    }
}
#[doc = r" struct that holds internal parser data,"]
#[doc = r" including data stack for each non-terminal,"]
#[doc = r" and state stack for DFA"]
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut
)]
pub struct GrammarStack {
    __rustylr_generated_terminal_stack: Vec<Lexed>,
    __rustylr_generated_stack_1: Vec<RuleDefArgs>,
    __rustylr_generated_stack_2: Vec<Option<Group>>,
    __rustylr_generated_stack_3: Vec<Vec<RuleLineArgs>>,
    __rustylr_generated_stack_4: Vec<RuleLineArgs>,
    __rustylr_generated_stack_5: Vec<(Option<Ident>, PatternArgs)>,
    __rustylr_generated_stack_6: Vec<TerminalSetItem>,
    __rustylr_generated_stack_7: Vec<TerminalSet>,
    __rustylr_generated_stack_8: Vec<PatternArgs>,
    __rustylr_generated_stack_9: Vec<(Ident, TokenStream)>,
    __rustylr_generated_stack_10: Vec<TokenStream>,
    __rustylr_generated_stack_11: Vec<Ident>,
    __rustylr_generated_stack_12: Vec<(Span, TokenStream)>,
    __rustylr_generated_stack_13: Vec<TerminalSetOrIdent>,
    __rustylr_generated_stack_14: Vec<ReduceType>,
    __rustylr_generated_stack_15: Vec<(TerminalSetOrIdent, ReduceType)>,
    __rustylr_generated_stack_16: Vec<Vec<(Option<Ident>, PatternArgs)>>,
    __rustylr_generated_stack_17: Vec<Option<Lexed>>,
    __rustylr_generated_stack_18: Vec<Vec<TerminalSetItem>>,
    __rustylr_generated_stack_19: Vec<Vec<PatternArgs>>,
    __rustylr_generated_stack_20: Vec<Vec<Lexed>>,
}
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut,
    dead_code
)]
impl GrammarStack {
    fn reduce_Rule_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RuleLines = self.__rustylr_generated_stack_3.pop().unwrap();
        let mut colon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RuleType = self.__rustylr_generated_stack_2.pop().unwrap();
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_1.push({
            let ident = if let Lexed::Ident(ident) = ident {
                ident
            } else {
                unreachable!("Rule-Ident");
            };
            if let Lexed::Colon(colon) = colon {
                let span = colon.span();
                if let Some(fisrt) = RuleLines.first_mut() {
                    fisrt.separator_span = span;
                }
            } else {
                unreachable!("Rule-Colon2");
            }
            RuleDefArgs {
                name: ident,
                typename: RuleType.map(|t| t.stream()),
                rule_lines: RuleLines,
            }
        });
        Ok(())
    }
    fn reduce_RuleType_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut parengroup = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_2.push({
            if let Lexed::ParenGroup(group) = parengroup {
                group
            } else {
                unreachable!("RuleType - Group");
            }
        });
        Ok(())
    }
    fn reduce_RuleType_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        self.__rustylr_generated_stack_2.push({ None });
        Ok(())
    }
    fn reduce_RuleLines_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut RuleLine = self.__rustylr_generated_stack_4.pop().unwrap();
        let mut pipe = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RuleLines = self.__rustylr_generated_stack_3.pop().unwrap();
        self.__rustylr_generated_stack_3.push({
            if let Lexed::Pipe(punct) = pipe {
                RuleLine.separator_span = punct.span();
                RuleLines.push(RuleLine);
            }
            RuleLines
        });
        Ok(())
    }
    fn reduce_RuleLines_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut RuleLine = self.__rustylr_generated_stack_4.pop().unwrap();
        self.__rustylr_generated_stack_3.push({ vec![RuleLine] });
        Ok(())
    }
    fn reduce_RuleLine_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut Action = self.__rustylr_generated_stack_2.pop().unwrap();
        let mut TokenMapped = self.__rustylr_generated_stack_16.pop().unwrap();
        self.__rustylr_generated_stack_4.push({
            RuleLineArgs {
                tokens: TokenMapped,
                reduce_action: Action.map(|action| action.to_token_stream()),
                separator_span: Span::call_site(),
                id: 0,
            }
        });
        Ok(())
    }
    fn reduce_TokenMapped_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_5.push({ (None, Pattern) });
        Ok(())
    }
    fn reduce_TokenMapped_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        let mut equal = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_5.push({
            if let Lexed::Ident(ident) = ident {
                (Some(ident), Pattern)
            } else {
                unreachable!("Token-Ident");
            }
        });
        Ok(())
    }
    fn reduce_TerminalSetItem_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_6.push({
            let ident = if let Lexed::Ident(ident) = ident {
                ident
            } else {
                unreachable!("TerminalSetItem-Range1");
            };
            TerminalSetItem::Terminal(ident)
        });
        Ok(())
    }
    fn reduce_TerminalSetItem_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut last = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut minus = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut first = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_6.push({
            let first = if let Lexed::Ident(first) = first {
                first
            } else {
                unreachable!("TerminalSetItem-Range1");
            };
            let last = if let Lexed::Ident(last) = last {
                last
            } else {
                unreachable!("TerminalSetItem-Range3");
            };
            TerminalSetItem::Range(first, last)
        });
        Ok(())
    }
    fn reduce_TerminalSet_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut rbracket = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut TerminalSetItem = self.__rustylr_generated_stack_18.pop().unwrap();
        let mut caret = self.__rustylr_generated_stack_17.pop().unwrap();
        let mut lbracket = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_7.push({
            let open_span = if let Lexed::LBracket(lbracket) = lbracket {
                lbracket
            } else {
                unreachable!("TerminalSet-Open");
            };
            let close_span = if let Lexed::RBracket(rbracket) = rbracket {
                rbracket
            } else {
                unreachable!("TerminalSet-Close");
            };
            TerminalSet {
                negate: caret.is_some(),
                items: TerminalSetItem,
                open_span,
                close_span,
            }
        });
        Ok(())
    }
    fn reduce_Pattern_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_8.push({
            if let Lexed::Ident(ident) = ident {
                PatternArgs::Ident(ident)
            } else {
                unreachable!("Pattern-Ident");
            }
        });
        Ok(())
    }
    fn reduce_Pattern_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut plus = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_8.push({
            if let Lexed::Plus(plus) = plus {
                PatternArgs::Plus(Box::new(Pattern), plus.span())
            } else {
                unreachable!("Pattern-Plus");
            }
        });
        Ok(())
    }
    fn reduce_Pattern_2(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut star = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_8.push({
            if let Lexed::Star(star) = star {
                PatternArgs::Star(Box::new(Pattern), star.span())
            } else {
                unreachable!("Pattern-Star");
            }
        });
        Ok(())
    }
    fn reduce_Pattern_3(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut question = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_8.push({
            if let Lexed::Question(question) = question {
                PatternArgs::Question(Box::new(Pattern), question.span())
            } else {
                unreachable!("Pattern-Question");
            }
        });
        Ok(())
    }
    fn reduce_Pattern_4(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut exclamation = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_8.push({
            if let Lexed::Exclamation(exclamation) = exclamation {
                PatternArgs::Exclamation(Box::new(Pattern), exclamation.span())
            } else {
                unreachable!("Pattern-Exclamation");
            }
        });
        Ok(())
    }
    fn reduce_Pattern_5(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut TerminalSet = self.__rustylr_generated_stack_7.pop().unwrap();
        self.__rustylr_generated_stack_8
            .push({ PatternArgs::TerminalSet(TerminalSet) });
        Ok(())
    }
    fn reduce_Pattern_6(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut TerminalSetOrIdent = self.__rustylr_generated_stack_13.pop().unwrap();
        let mut slash = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Pattern = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_8
            .push({ PatternArgs::Lookaheads(Box::new(Pattern), TerminalSetOrIdent) });
        Ok(())
    }
    fn reduce_Pattern_7(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut rparen = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Pattern = self.__rustylr_generated_stack_19.pop().unwrap();
        let mut lparen = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_8.push({
            let open = if let Lexed::LParen(lparen) = lparen {
                lparen
            } else {
                unreachable!("Pattern-Group-Open");
            };
            let close = if let Lexed::RParen(rparen) = rparen {
                rparen
            } else {
                unreachable!("Pattern-Group-Close");
            };
            PatternArgs::Group(Pattern, open, close)
        });
        Ok(())
    }
    fn reduce_Action_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut bracegroup = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_2.push({
            if let Lexed::BraceGroup(group) = bracegroup {
                group
            } else {
                unreachable!("Action0");
            }
        });
        Ok(())
    }
    fn reduce_Action_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        self.__rustylr_generated_stack_2.push({ None });
        Ok(())
    }
    fn reduce_TokenDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RustCode = self.__rustylr_generated_stack_10.pop().unwrap();
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut token = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_9.push({
            if let Lexed::Ident(ident) = ident {
                (ident, RustCode)
            } else {
                unreachable!("TokenDef-Ident");
            }
        });
        Ok(())
    }
    fn reduce_RustCode_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut t = self.__rustylr_generated_stack_20.pop().unwrap();
        self.__rustylr_generated_stack_10.push({
            let mut tokens = TokenStream::new();
            for token in t.into_iter() {
                token.append_to_stream(&mut tokens);
            }
            tokens
        });
        Ok(())
    }
    fn reduce_StartDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut start = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_11.push({
            if let Lexed::Ident(ident) = ident {
                ident
            } else {
                unreachable!("StartDef-Ident");
            }
        });
        Ok(())
    }
    fn reduce_EofDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RustCode = self.__rustylr_generated_stack_10.pop().unwrap();
        let mut eofdef = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_12
            .push({ (eofdef.span(), RustCode) });
        Ok(())
    }
    fn reduce_TokenTypeDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RustCode = self.__rustylr_generated_stack_10.pop().unwrap();
        let mut tokentype = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_12
            .push({ (tokentype.span(), RustCode) });
        Ok(())
    }
    fn reduce_UserDataDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RustCode = self.__rustylr_generated_stack_10.pop().unwrap();
        let mut userdata = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_12
            .push({ (userdata.span(), RustCode) });
        Ok(())
    }
    fn reduce_TerminalSetOrIdent_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut TerminalSet = self.__rustylr_generated_stack_7.pop().unwrap();
        self.__rustylr_generated_stack_13
            .push({ TerminalSetOrIdent::TerminalSet(TerminalSet) });
        Ok(())
    }
    fn reduce_TerminalSetOrIdent_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut ident = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_13.push({
            if let Lexed::Ident(ident) = ident {
                TerminalSetOrIdent::Ident(ident)
            } else {
                unreachable!("TerminalSetOrIdent-Ident");
            }
        });
        Ok(())
    }
    fn reduce_ReduceType_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut left = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_14.push({ ReduceType::Left });
        Ok(())
    }
    fn reduce_ReduceType_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut right = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_14
            .push({ ReduceType::Right });
        Ok(())
    }
    fn reduce_ReduceDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut TerminalSetOrIdent = self.__rustylr_generated_stack_13.pop().unwrap();
        let mut reducetype = self.__rustylr_generated_stack_14.pop().unwrap();
        self.__rustylr_generated_stack_15
            .push({ (TerminalSetOrIdent, reducetype) });
        Ok(())
    }
    fn reduce_ErrorDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RustCode = self.__rustylr_generated_stack_10.pop().unwrap();
        let mut errortype = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_12
            .push({ (errortype.span(), RustCode) });
        Ok(())
    }
    fn reduce_ModulePrefixDef_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut RustCode = self.__rustylr_generated_stack_10.pop().unwrap();
        let mut moduleprefix = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_12
            .push({ (moduleprefix.span(), RustCode) });
        Ok(())
    }
    fn reduce_Glr_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut semicolon = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut glr = self.__rustylr_generated_terminal_stack.pop().unwrap();
        Ok(())
    }
    fn reduce_GrammarLine_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut Rule = self.__rustylr_generated_stack_1.pop().unwrap();
        {
            data.rules.push(Rule);
        }
        Ok(())
    }
    fn reduce_GrammarLine_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut TokenDef = self.__rustylr_generated_stack_9.pop().unwrap();
        {
            data.terminals.push(TokenDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_2(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut StartDef = self.__rustylr_generated_stack_11.pop().unwrap();
        {
            data.start_rule_name.push(StartDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_3(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut EofDef = self.__rustylr_generated_stack_12.pop().unwrap();
        {
            data.eof.push(EofDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_4(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut TokenTypeDef = self.__rustylr_generated_stack_12.pop().unwrap();
        {
            data.token_typename.push(TokenTypeDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_5(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut UserDataDef = self.__rustylr_generated_stack_12.pop().unwrap();
        {
            data.userdata_typename.push(UserDataDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_6(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut ReduceDef = self.__rustylr_generated_stack_15.pop().unwrap();
        {
            data.reduce_types.push(ReduceDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_7(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut ErrorDef = self.__rustylr_generated_stack_12.pop().unwrap();
        {
            data.error_typename.push(ErrorDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_8(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut ModulePrefixDef = self.__rustylr_generated_stack_12.pop().unwrap();
        {
            data.module_prefix.push(ModulePrefixDef);
        }
        Ok(())
    }
    fn reduce_GrammarLine_9(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        {
            data.glr = true;
        }
        Ok(())
    }
    fn reduce_Grammar_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        Ok(())
    }
    fn reduce__TokenMapped_Plus23_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_stack_5.pop().unwrap();
        self.__rustylr_generated_stack_16.push({ vec![A] });
        Ok(())
    }
    fn reduce__TokenMapped_Plus23_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_stack_5.pop().unwrap();
        let mut Ap = self.__rustylr_generated_stack_16.pop().unwrap();
        self.__rustylr_generated_stack_16.push({
            Ap.push(A);
            Ap
        });
        Ok(())
    }
    fn reduce__TokenMapped_Star24_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut Ap = self.__rustylr_generated_stack_16.pop().unwrap();
        self.__rustylr_generated_stack_16.push({ Ap });
        Ok(())
    }
    fn reduce__TokenMapped_Star24_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        self.__rustylr_generated_stack_16.push({ vec![] });
        Ok(())
    }
    fn reduce__caret_Question25_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_17.push({ Some(A) });
        Ok(())
    }
    fn reduce__caret_Question25_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        self.__rustylr_generated_stack_17.push({ None });
        Ok(())
    }
    fn reduce__TerminalSetItem_Plus26_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_stack_6.pop().unwrap();
        self.__rustylr_generated_stack_18.push({ vec![A] });
        Ok(())
    }
    fn reduce__TerminalSetItem_Plus26_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_stack_6.pop().unwrap();
        let mut Ap = self.__rustylr_generated_stack_18.pop().unwrap();
        self.__rustylr_generated_stack_18.push({
            Ap.push(A);
            Ap
        });
        Ok(())
    }
    fn reduce__TerminalSetItem_Star27_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut Ap = self.__rustylr_generated_stack_18.pop().unwrap();
        self.__rustylr_generated_stack_18.push({ Ap });
        Ok(())
    }
    fn reduce__TerminalSetItem_Star27_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        self.__rustylr_generated_stack_18.push({ vec![] });
        Ok(())
    }
    fn reduce__Pattern_Plus28_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_stack_8.pop().unwrap();
        self.__rustylr_generated_stack_19.push({ vec![A] });
        Ok(())
    }
    fn reduce__Pattern_Plus28_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_stack_8.pop().unwrap();
        let mut Ap = self.__rustylr_generated_stack_19.pop().unwrap();
        self.__rustylr_generated_stack_19.push({
            Ap.push(A);
            Ap
        });
        Ok(())
    }
    fn reduce__TerminalSet29_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_2(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_3(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_4(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_5(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_6(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_7(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_8(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_9(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_10(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_11(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_12(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_13(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_14(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_15(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_16(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce__TerminalSet29_17(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut term = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_terminal_stack.push(term);
        Ok(())
    }
    fn reduce___TerminalSet29_Plus30_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_terminal_stack.pop().unwrap();
        self.__rustylr_generated_stack_20.push({ vec![A] });
        Ok(())
    }
    fn reduce___TerminalSet29_Plus30_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        let mut A = self.__rustylr_generated_terminal_stack.pop().unwrap();
        let mut Ap = self.__rustylr_generated_stack_20.pop().unwrap();
        self.__rustylr_generated_stack_20.push({
            Ap.push(A);
            Ap
        });
        Ok(())
    }
    fn reduce__GrammarLine_Plus31_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        Ok(())
    }
    fn reduce__GrammarLine_Plus31_1(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        Ok(())
    }
    fn reduce_Augmented_0(
        &mut self,
        lookahead: &Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), ::rusty_lr_core::DefaultReduceActionError> {
        self.__rustylr_generated_terminal_stack.pop();
        Ok(())
    }
}
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut,
    dead_code
)]
impl ::rusty_lr_core::lr::Stack for GrammarStack {
    type Term = Lexed;
    type NonTerm = GrammarNonTerminals;
    type ReduceActionError = ::rusty_lr_core::DefaultReduceActionError;
    type UserData = GrammarArgs;
    type StartType = ();
    fn new() -> Self {
        Self {
            __rustylr_generated_terminal_stack: Vec::new(),
            __rustylr_generated_stack_1: Vec::new(),
            __rustylr_generated_stack_2: Vec::new(),
            __rustylr_generated_stack_3: Vec::new(),
            __rustylr_generated_stack_4: Vec::new(),
            __rustylr_generated_stack_5: Vec::new(),
            __rustylr_generated_stack_6: Vec::new(),
            __rustylr_generated_stack_7: Vec::new(),
            __rustylr_generated_stack_8: Vec::new(),
            __rustylr_generated_stack_9: Vec::new(),
            __rustylr_generated_stack_10: Vec::new(),
            __rustylr_generated_stack_11: Vec::new(),
            __rustylr_generated_stack_12: Vec::new(),
            __rustylr_generated_stack_13: Vec::new(),
            __rustylr_generated_stack_14: Vec::new(),
            __rustylr_generated_stack_15: Vec::new(),
            __rustylr_generated_stack_16: Vec::new(),
            __rustylr_generated_stack_17: Vec::new(),
            __rustylr_generated_stack_18: Vec::new(),
            __rustylr_generated_stack_19: Vec::new(),
            __rustylr_generated_stack_20: Vec::new(),
        }
    }
    fn push(&mut self, term: Self::Term) {
        self.__rustylr_generated_terminal_stack.push(term);
    }
    fn reduce(
        &mut self,
        rustylr_macro_generated_ruleid__: usize,
        data: &mut Self::UserData,
        lookahead: &Self::Term,
    ) -> Result<(), Self::ReduceActionError> {
        match rustylr_macro_generated_ruleid__ {
            0usize => self.reduce_Rule_0(lookahead, data),
            1usize => self.reduce_RuleType_0(lookahead, data),
            2usize => self.reduce_RuleType_1(lookahead, data),
            3usize => self.reduce_RuleLines_0(lookahead, data),
            4usize => self.reduce_RuleLines_1(lookahead, data),
            5usize => self.reduce_RuleLine_0(lookahead, data),
            6usize => self.reduce_TokenMapped_0(lookahead, data),
            7usize => self.reduce_TokenMapped_1(lookahead, data),
            8usize => self.reduce_TerminalSetItem_0(lookahead, data),
            9usize => self.reduce_TerminalSetItem_1(lookahead, data),
            10usize => self.reduce_TerminalSet_0(lookahead, data),
            11usize => self.reduce_Pattern_0(lookahead, data),
            12usize => self.reduce_Pattern_1(lookahead, data),
            13usize => self.reduce_Pattern_2(lookahead, data),
            14usize => self.reduce_Pattern_3(lookahead, data),
            15usize => self.reduce_Pattern_4(lookahead, data),
            16usize => self.reduce_Pattern_5(lookahead, data),
            17usize => self.reduce_Pattern_6(lookahead, data),
            18usize => self.reduce_Pattern_7(lookahead, data),
            19usize => self.reduce_Action_0(lookahead, data),
            20usize => self.reduce_Action_1(lookahead, data),
            21usize => self.reduce_TokenDef_0(lookahead, data),
            22usize => self.reduce_RustCode_0(lookahead, data),
            23usize => self.reduce_StartDef_0(lookahead, data),
            24usize => self.reduce_EofDef_0(lookahead, data),
            25usize => self.reduce_TokenTypeDef_0(lookahead, data),
            26usize => self.reduce_UserDataDef_0(lookahead, data),
            27usize => self.reduce_TerminalSetOrIdent_0(lookahead, data),
            28usize => self.reduce_TerminalSetOrIdent_1(lookahead, data),
            29usize => self.reduce_ReduceType_0(lookahead, data),
            30usize => self.reduce_ReduceType_1(lookahead, data),
            31usize => self.reduce_ReduceDef_0(lookahead, data),
            32usize => self.reduce_ErrorDef_0(lookahead, data),
            33usize => self.reduce_ModulePrefixDef_0(lookahead, data),
            34usize => self.reduce_Glr_0(lookahead, data),
            35usize => self.reduce_GrammarLine_0(lookahead, data),
            36usize => self.reduce_GrammarLine_1(lookahead, data),
            37usize => self.reduce_GrammarLine_2(lookahead, data),
            38usize => self.reduce_GrammarLine_3(lookahead, data),
            39usize => self.reduce_GrammarLine_4(lookahead, data),
            40usize => self.reduce_GrammarLine_5(lookahead, data),
            41usize => self.reduce_GrammarLine_6(lookahead, data),
            42usize => self.reduce_GrammarLine_7(lookahead, data),
            43usize => self.reduce_GrammarLine_8(lookahead, data),
            44usize => self.reduce_GrammarLine_9(lookahead, data),
            45usize => self.reduce_Grammar_0(lookahead, data),
            46usize => self.reduce__TokenMapped_Plus23_0(lookahead, data),
            47usize => self.reduce__TokenMapped_Plus23_1(lookahead, data),
            48usize => self.reduce__TokenMapped_Star24_0(lookahead, data),
            49usize => self.reduce__TokenMapped_Star24_1(lookahead, data),
            50usize => self.reduce__caret_Question25_0(lookahead, data),
            51usize => self.reduce__caret_Question25_1(lookahead, data),
            52usize => self.reduce__TerminalSetItem_Plus26_0(lookahead, data),
            53usize => self.reduce__TerminalSetItem_Plus26_1(lookahead, data),
            54usize => self.reduce__TerminalSetItem_Star27_0(lookahead, data),
            55usize => self.reduce__TerminalSetItem_Star27_1(lookahead, data),
            56usize => self.reduce__Pattern_Plus28_0(lookahead, data),
            57usize => self.reduce__Pattern_Plus28_1(lookahead, data),
            58usize => self.reduce__TerminalSet29_0(lookahead, data),
            59usize => self.reduce__TerminalSet29_1(lookahead, data),
            60usize => self.reduce__TerminalSet29_2(lookahead, data),
            61usize => self.reduce__TerminalSet29_3(lookahead, data),
            62usize => self.reduce__TerminalSet29_4(lookahead, data),
            63usize => self.reduce__TerminalSet29_5(lookahead, data),
            64usize => self.reduce__TerminalSet29_6(lookahead, data),
            65usize => self.reduce__TerminalSet29_7(lookahead, data),
            66usize => self.reduce__TerminalSet29_8(lookahead, data),
            67usize => self.reduce__TerminalSet29_9(lookahead, data),
            68usize => self.reduce__TerminalSet29_10(lookahead, data),
            69usize => self.reduce__TerminalSet29_11(lookahead, data),
            70usize => self.reduce__TerminalSet29_12(lookahead, data),
            71usize => self.reduce__TerminalSet29_13(lookahead, data),
            72usize => self.reduce__TerminalSet29_14(lookahead, data),
            73usize => self.reduce__TerminalSet29_15(lookahead, data),
            74usize => self.reduce__TerminalSet29_16(lookahead, data),
            75usize => self.reduce__TerminalSet29_17(lookahead, data),
            76usize => self.reduce___TerminalSet29_Plus30_0(lookahead, data),
            77usize => self.reduce___TerminalSet29_Plus30_1(lookahead, data),
            78usize => self.reduce__GrammarLine_Plus31_0(lookahead, data),
            79usize => self.reduce__GrammarLine_Plus31_1(lookahead, data),
            80usize => self.reduce_Augmented_0(lookahead, data),
            _ => {
                unreachable!("Invalid Rule: {}", rustylr_macro_generated_ruleid__);
            }
        }
    }
    fn pop_start(&mut self) -> Self::StartType {
        ()
    }
}
#[doc = r" struct that holds parser data, DFA tables"]
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut
)]
pub struct GrammarParser {
    #[doc = r" production rules"]
    pub rules: Vec<GrammarRule>,
    #[doc = r" states"]
    pub states: Vec<GrammarState>,
}
impl ::rusty_lr_core::lr::Parser for GrammarParser {
    type Term = Lexed;
    type NonTerm = GrammarNonTerminals;
    fn get_rules(&self) -> &[GrammarRule] {
        &self.rules
    }
    fn get_states(&self) -> &[GrammarState] {
        &self.states
    }
}
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut
)]
impl GrammarParser {
    #[doc = r" feed one terminal to parser, and update state stack"]
    pub fn feed(
        &self,
        context: &mut GrammarContext,
        term: Lexed,
        data: &mut GrammarArgs,
    ) -> Result<(), GrammarParseError> {
        ::rusty_lr_core::lr::feed(self, context, term, data)
    }
    #[doc = r" Create new context for parsing"]
    #[inline]
    pub fn begin(&self) -> GrammarContext {
        GrammarContext::new()
    }
    #[doc = r" Create new parser instance."]
    #[doc = r" Parser can be reused with different context, for multiple parsing."]
    pub fn new() -> Self {
        let __rustylr_terminals = vec![
            Lexed::Ident(Ident::new("id", Span::call_site())),
            Lexed::Colon(punct!(':')),
            Lexed::Semicolon(punct!(';')),
            Lexed::Pipe(punct!('|')),
            Lexed::Percent(punct!('%')),
            Lexed::Equal(punct!('=')),
            Lexed::Plus(punct!('+')),
            Lexed::Star(punct!('*')),
            Lexed::Question(punct!('?')),
            Lexed::Caret(punct!('^')),
            Lexed::Minus(punct!('-')),
            Lexed::Exclamation(punct!('!')),
            Lexed::Slash(punct!('/')),
            Lexed::OtherPunct(punct!('.')),
            Lexed::Literal(None),
            Lexed::ParenGroup(None),
            Lexed::BraceGroup(None),
            Lexed::BracketGroup(None),
            Lexed::NoneGroup(None),
            Lexed::LParen(Span::call_site()),
            Lexed::RParen(Span::call_site()),
            Lexed::LBrace(Span::call_site()),
            Lexed::RBrace(Span::call_site()),
            Lexed::LBracket(Span::call_site()),
            Lexed::RBracket(Span::call_site()),
            Lexed::Left(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::Right(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::Token(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::Start(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::EofDef(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::TokenType(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::UserData(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::ErrorType(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::ModulePrefix(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::Glr(punct!('%'), Ident::new("id", Span::call_site())),
            Lexed::Eof,
        ];
        const RUSTYLR_RULES_TOKENS: &[&[::rusty_lr_core::Token<u8, GrammarNonTerminals>]] = &[
            &[
                ::rusty_lr_core::Token::Term(0),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RuleType),
                ::rusty_lr_core::Token::Term(1),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RuleLines),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[::rusty_lr_core::Token::Term(15)],
            &[],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RuleLines),
                ::rusty_lr_core::Token::Term(3),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RuleLine),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::RuleLine,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_TokenMapped_Star24),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Action),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::Pattern,
            )],
            &[
                ::rusty_lr_core::Token::Term(0),
                ::rusty_lr_core::Token::Term(5),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
            ],
            &[::rusty_lr_core::Token::Term(0)],
            &[
                ::rusty_lr_core::Token::Term(0),
                ::rusty_lr_core::Token::Term(10),
                ::rusty_lr_core::Token::Term(0),
            ],
            &[
                ::rusty_lr_core::Token::Term(23),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_caret_Question25),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_TerminalSetItem_Star27),
                ::rusty_lr_core::Token::Term(24),
            ],
            &[::rusty_lr_core::Token::Term(0)],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
                ::rusty_lr_core::Token::Term(6),
            ],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
                ::rusty_lr_core::Token::Term(7),
            ],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
                ::rusty_lr_core::Token::Term(8),
            ],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
                ::rusty_lr_core::Token::Term(11),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::TerminalSet,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
                ::rusty_lr_core::Token::Term(12),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::TerminalSetOrIdent),
            ],
            &[
                ::rusty_lr_core::Token::Term(19),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_Pattern_Plus28),
                ::rusty_lr_core::Token::Term(20),
            ],
            &[::rusty_lr_core::Token::Term(16)],
            &[],
            &[
                ::rusty_lr_core::Token::Term(27),
                ::rusty_lr_core::Token::Term(0),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RustCode),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::__TerminalSet29_Plus30,
            )],
            &[
                ::rusty_lr_core::Token::Term(28),
                ::rusty_lr_core::Token::Term(0),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[
                ::rusty_lr_core::Token::Term(29),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RustCode),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[
                ::rusty_lr_core::Token::Term(30),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RustCode),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[
                ::rusty_lr_core::Token::Term(31),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RustCode),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::TerminalSet,
            )],
            &[::rusty_lr_core::Token::Term(0)],
            &[::rusty_lr_core::Token::Term(25)],
            &[::rusty_lr_core::Token::Term(26)],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::ReduceType),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::TerminalSetOrIdent),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[
                ::rusty_lr_core::Token::Term(32),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RustCode),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[
                ::rusty_lr_core::Token::Term(33),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::RustCode),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[
                ::rusty_lr_core::Token::Term(34),
                ::rusty_lr_core::Token::Term(2),
            ],
            &[::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Rule)],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::TokenDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::StartDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::EofDef)],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::TokenTypeDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::UserDataDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::ReduceDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::ErrorDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::ModulePrefixDef,
            )],
            &[::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Glr)],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::_GrammarLine_Plus31,
            )],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::TokenMapped,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_TokenMapped_Plus23),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::TokenMapped),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::_TokenMapped_Plus23,
            )],
            &[],
            &[::rusty_lr_core::Token::Term(9)],
            &[],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::TerminalSetItem,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_TerminalSetItem_Plus26),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::TerminalSetItem),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::_TerminalSetItem_Plus26,
            )],
            &[],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::Pattern,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_Pattern_Plus28),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Pattern),
            ],
            &[::rusty_lr_core::Token::Term(0)],
            &[::rusty_lr_core::Token::Term(1)],
            &[::rusty_lr_core::Token::Term(3)],
            &[::rusty_lr_core::Token::Term(4)],
            &[::rusty_lr_core::Token::Term(5)],
            &[::rusty_lr_core::Token::Term(6)],
            &[::rusty_lr_core::Token::Term(7)],
            &[::rusty_lr_core::Token::Term(8)],
            &[::rusty_lr_core::Token::Term(9)],
            &[::rusty_lr_core::Token::Term(10)],
            &[::rusty_lr_core::Token::Term(11)],
            &[::rusty_lr_core::Token::Term(12)],
            &[::rusty_lr_core::Token::Term(13)],
            &[::rusty_lr_core::Token::Term(14)],
            &[::rusty_lr_core::Token::Term(15)],
            &[::rusty_lr_core::Token::Term(16)],
            &[::rusty_lr_core::Token::Term(17)],
            &[::rusty_lr_core::Token::Term(18)],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::_TerminalSet29,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::__TerminalSet29_Plus30),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_TerminalSet29),
            ],
            &[::rusty_lr_core::Token::NonTerm(
                GrammarNonTerminals::GrammarLine,
            )],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::GrammarLine),
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::_GrammarLine_Plus31),
            ],
            &[
                ::rusty_lr_core::Token::NonTerm(GrammarNonTerminals::Grammar),
                ::rusty_lr_core::Token::Term(35),
            ],
        ];
        const RUSTYLR_RULES_NAME: &[GrammarNonTerminals] = &[
            GrammarNonTerminals::Rule,
            GrammarNonTerminals::RuleType,
            GrammarNonTerminals::RuleType,
            GrammarNonTerminals::RuleLines,
            GrammarNonTerminals::RuleLines,
            GrammarNonTerminals::RuleLine,
            GrammarNonTerminals::TokenMapped,
            GrammarNonTerminals::TokenMapped,
            GrammarNonTerminals::TerminalSetItem,
            GrammarNonTerminals::TerminalSetItem,
            GrammarNonTerminals::TerminalSet,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Pattern,
            GrammarNonTerminals::Action,
            GrammarNonTerminals::Action,
            GrammarNonTerminals::TokenDef,
            GrammarNonTerminals::RustCode,
            GrammarNonTerminals::StartDef,
            GrammarNonTerminals::EofDef,
            GrammarNonTerminals::TokenTypeDef,
            GrammarNonTerminals::UserDataDef,
            GrammarNonTerminals::TerminalSetOrIdent,
            GrammarNonTerminals::TerminalSetOrIdent,
            GrammarNonTerminals::ReduceType,
            GrammarNonTerminals::ReduceType,
            GrammarNonTerminals::ReduceDef,
            GrammarNonTerminals::ErrorDef,
            GrammarNonTerminals::ModulePrefixDef,
            GrammarNonTerminals::Glr,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::GrammarLine,
            GrammarNonTerminals::Grammar,
            GrammarNonTerminals::_TokenMapped_Plus23,
            GrammarNonTerminals::_TokenMapped_Plus23,
            GrammarNonTerminals::_TokenMapped_Star24,
            GrammarNonTerminals::_TokenMapped_Star24,
            GrammarNonTerminals::_caret_Question25,
            GrammarNonTerminals::_caret_Question25,
            GrammarNonTerminals::_TerminalSetItem_Plus26,
            GrammarNonTerminals::_TerminalSetItem_Plus26,
            GrammarNonTerminals::_TerminalSetItem_Star27,
            GrammarNonTerminals::_TerminalSetItem_Star27,
            GrammarNonTerminals::_Pattern_Plus28,
            GrammarNonTerminals::_Pattern_Plus28,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::_TerminalSet29,
            GrammarNonTerminals::__TerminalSet29_Plus30,
            GrammarNonTerminals::__TerminalSet29_Plus30,
            GrammarNonTerminals::_GrammarLine_Plus31,
            GrammarNonTerminals::_GrammarLine_Plus31,
            GrammarNonTerminals::Augmented,
        ];
        const RUSTYLR_RULES_ID: &[u8] = &[
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ];
        let rules: Vec<GrammarRule> = RUSTYLR_RULES_NAME
            .iter()
            .zip(RUSTYLR_RULES_TOKENS.iter().zip(RUSTYLR_RULES_ID.iter()))
            .map(|(name, (tokens, id))| GrammarRule {
                name: *name,
                rule: tokens
                    .iter()
                    .map(|token| match token {
                        ::rusty_lr_core::Token::Term(term) => ::rusty_lr_core::Token::Term(
                            __rustylr_terminals[*term as usize].clone(),
                        ),
                        ::rusty_lr_core::Token::NonTerm(nonterm) => {
                            ::rusty_lr_core::Token::NonTerm(*nonterm)
                        }
                    })
                    .collect(),
                id: *id as usize,
            })
            .collect();
        const RUSTYLR_REDUCE_TERMINALS_CACHE: &[&[u8]] = &[
            &[1],
            &[2, 3, 16],
            &[0, 2, 3, 6, 7, 8, 11, 12, 16, 19, 23],
            &[0, 6, 7, 8, 11, 12, 19, 20, 23],
            &[0, 24],
            &[24],
            &[0, 19, 20, 23],
            &[0, 2, 3, 16, 19, 23],
            &[0, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
            &[2, 3],
            &[0, 23],
            &[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            ],
            &[2],
            &[35],
        ];
        const RUSTYLR_RULESET_SHIFTED0_CACHE: &[&[u8]] = &[
            &[
                0, 21, 23, 24, 25, 26, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
                44, 45, 78, 79, 80,
            ],
            &[1, 2],
            &[],
            &[
                3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 46, 47, 48, 49,
            ],
            &[10, 11, 12, 13, 14, 15, 16, 17, 18],
            &[10, 11, 12, 13, 14, 15, 16, 17, 18, 56, 57],
            &[50, 51],
            &[8, 9, 52, 53, 54, 55],
            &[8, 9],
            &[10, 27, 28],
            &[5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 46, 47, 48, 49],
            &[6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 18],
            &[19, 20],
            &[
                22, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
            ],
            &[
                58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
            ],
            &[
                0, 21, 23, 24, 25, 26, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
                44, 78, 79,
            ],
        ];
        const RUSTYLR_SHIFT_TERM_MAP: &[&[(u8, u8)]] = &[
            &[
                (0, 1),
                (25, 63),
                (26, 64),
                (27, 65),
                (28, 90),
                (29, 93),
                (30, 96),
                (31, 99),
                (32, 102),
                (33, 105),
                (34, 108),
            ],
            &[(15, 2)],
            &[],
            &[(1, 4)],
            &[(0, 5), (19, 8), (23, 37)],
            &[(5, 6)],
            &[(0, 7), (19, 8), (23, 37)],
            &[],
            &[(0, 9), (19, 10), (23, 11)],
            &[],
            &[(0, 9), (19, 10), (23, 11)],
            &[(9, 12)],
            &[],
            &[(0, 14)],
            &[(10, 15)],
            &[(0, 16)],
            &[],
            &[],
            &[(0, 14)],
            &[],
            &[(24, 21)],
            &[],
            &[],
            &[(6, 24), (7, 25), (8, 26), (11, 27), (12, 28)],
            &[],
            &[],
            &[],
            &[],
            &[(0, 29), (23, 11)],
            &[],
            &[],
            &[],
            &[(0, 9), (19, 10), (20, 33), (23, 11)],
            &[],
            &[(6, 24), (7, 25), (8, 26), (11, 27), (12, 28)],
            &[(0, 9), (19, 10), (20, 36), (23, 11)],
            &[],
            &[(9, 12)],
            &[(0, 14)],
            &[(24, 40)],
            &[],
            &[],
            &[(6, 43), (7, 44), (8, 45), (11, 46), (12, 47)],
            &[],
            &[],
            &[],
            &[],
            &[(0, 48), (23, 37)],
            &[],
            &[],
            &[],
            &[(2, 52), (3, 53)],
            &[],
            &[(0, 5), (19, 8), (23, 37)],
            &[],
            &[],
            &[(6, 43), (7, 44), (8, 45), (11, 46), (12, 47)],
            &[(0, 5), (19, 8), (23, 37)],
            &[],
            &[(16, 60)],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[(0, 66)],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[(2, 86)],
            &[],
            &[],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[],
            &[(0, 91)],
            &[(2, 92)],
            &[],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[(2, 95)],
            &[],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[(2, 98)],
            &[],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[(2, 101)],
            &[],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[(2, 104)],
            &[],
            &[
                (0, 67),
                (1, 68),
                (3, 69),
                (4, 70),
                (5, 71),
                (6, 72),
                (7, 73),
                (8, 74),
                (9, 75),
                (10, 76),
                (11, 77),
                (12, 78),
                (13, 79),
                (14, 80),
                (15, 81),
                (16, 82),
                (17, 83),
                (18, 84),
            ],
            &[(2, 107)],
            &[],
            &[(2, 109)],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[(0, 117), (23, 118)],
            &[],
            &[(9, 12)],
            &[(0, 14)],
            &[(24, 121)],
            &[],
            &[],
            &[(2, 124)],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (0, 1),
                (25, 63),
                (26, 64),
                (27, 65),
                (28, 90),
                (29, 93),
                (30, 96),
                (31, 99),
                (32, 102),
                (33, 105),
                (34, 108),
            ],
            &[],
            &[(35, 132)],
            &[],
            &[],
        ];
        const RUSTYLR_SHIFT_NONTERM_MAP: &[&[(GrammarNonTerminals, u8)]] = &[
            &[
                (GrammarNonTerminals::EofDef, 113),
                (GrammarNonTerminals::ErrorDef, 126),
                (GrammarNonTerminals::Glr, 128),
                (GrammarNonTerminals::Grammar, 131),
                (GrammarNonTerminals::GrammarLine, 129),
                (GrammarNonTerminals::ModulePrefixDef, 127),
                (GrammarNonTerminals::ReduceDef, 125),
                (GrammarNonTerminals::ReduceType, 116),
                (GrammarNonTerminals::Rule, 110),
                (GrammarNonTerminals::StartDef, 112),
                (GrammarNonTerminals::TokenDef, 111),
                (GrammarNonTerminals::TokenTypeDef, 114),
                (GrammarNonTerminals::UserDataDef, 115),
                (GrammarNonTerminals::_GrammarLine_Plus31, 133),
            ],
            &[(GrammarNonTerminals::RuleType, 3)],
            &[],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 56),
                (GrammarNonTerminals::RuleLine, 62),
                (GrammarNonTerminals::RuleLines, 51),
                (GrammarNonTerminals::TerminalSet, 41),
                (GrammarNonTerminals::TokenMapped, 55),
                (GrammarNonTerminals::_TokenMapped_Plus23, 57),
                (GrammarNonTerminals::_TokenMapped_Star24, 59),
            ],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 42),
                (GrammarNonTerminals::TerminalSet, 41),
            ],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 23),
                (GrammarNonTerminals::TerminalSet, 22),
                (GrammarNonTerminals::_Pattern_Plus28, 35),
            ],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 23),
                (GrammarNonTerminals::TerminalSet, 22),
                (GrammarNonTerminals::_Pattern_Plus28, 32),
            ],
            &[(GrammarNonTerminals::_caret_Question25, 13)],
            &[],
            &[
                (GrammarNonTerminals::TerminalSetItem, 17),
                (GrammarNonTerminals::_TerminalSetItem_Plus26, 18),
                (GrammarNonTerminals::_TerminalSetItem_Star27, 20),
            ],
            &[],
            &[],
            &[],
            &[],
            &[(GrammarNonTerminals::TerminalSetItem, 19)],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::TerminalSet, 30),
                (GrammarNonTerminals::TerminalSetOrIdent, 31),
            ],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 34),
                (GrammarNonTerminals::TerminalSet, 22),
            ],
            &[],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 34),
                (GrammarNonTerminals::TerminalSet, 22),
            ],
            &[],
            &[(GrammarNonTerminals::_caret_Question25, 38)],
            &[
                (GrammarNonTerminals::TerminalSetItem, 17),
                (GrammarNonTerminals::_TerminalSetItem_Plus26, 18),
                (GrammarNonTerminals::_TerminalSetItem_Star27, 39),
            ],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::TerminalSet, 49),
                (GrammarNonTerminals::TerminalSetOrIdent, 50),
            ],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 56),
                (GrammarNonTerminals::RuleLine, 54),
                (GrammarNonTerminals::TerminalSet, 41),
                (GrammarNonTerminals::TokenMapped, 55),
                (GrammarNonTerminals::_TokenMapped_Plus23, 57),
                (GrammarNonTerminals::_TokenMapped_Star24, 59),
            ],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::Pattern, 56),
                (GrammarNonTerminals::TerminalSet, 41),
                (GrammarNonTerminals::TokenMapped, 58),
            ],
            &[],
            &[(GrammarNonTerminals::Action, 61)],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::RustCode, 85),
                (GrammarNonTerminals::_TerminalSet29, 87),
                (GrammarNonTerminals::__TerminalSet29_Plus30, 88),
            ],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[(GrammarNonTerminals::_TerminalSet29, 89)],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::RustCode, 94),
                (GrammarNonTerminals::_TerminalSet29, 87),
                (GrammarNonTerminals::__TerminalSet29_Plus30, 88),
            ],
            &[],
            &[],
            &[
                (GrammarNonTerminals::RustCode, 97),
                (GrammarNonTerminals::_TerminalSet29, 87),
                (GrammarNonTerminals::__TerminalSet29_Plus30, 88),
            ],
            &[],
            &[],
            &[
                (GrammarNonTerminals::RustCode, 100),
                (GrammarNonTerminals::_TerminalSet29, 87),
                (GrammarNonTerminals::__TerminalSet29_Plus30, 88),
            ],
            &[],
            &[],
            &[
                (GrammarNonTerminals::RustCode, 103),
                (GrammarNonTerminals::_TerminalSet29, 87),
                (GrammarNonTerminals::__TerminalSet29_Plus30, 88),
            ],
            &[],
            &[],
            &[
                (GrammarNonTerminals::RustCode, 106),
                (GrammarNonTerminals::_TerminalSet29, 87),
                (GrammarNonTerminals::__TerminalSet29_Plus30, 88),
            ],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::TerminalSet, 122),
                (GrammarNonTerminals::TerminalSetOrIdent, 123),
            ],
            &[],
            &[(GrammarNonTerminals::_caret_Question25, 119)],
            &[
                (GrammarNonTerminals::TerminalSetItem, 17),
                (GrammarNonTerminals::_TerminalSetItem_Plus26, 18),
                (GrammarNonTerminals::_TerminalSetItem_Star27, 120),
            ],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[],
            &[
                (GrammarNonTerminals::EofDef, 113),
                (GrammarNonTerminals::ErrorDef, 126),
                (GrammarNonTerminals::Glr, 128),
                (GrammarNonTerminals::GrammarLine, 129),
                (GrammarNonTerminals::ModulePrefixDef, 127),
                (GrammarNonTerminals::ReduceDef, 125),
                (GrammarNonTerminals::ReduceType, 116),
                (GrammarNonTerminals::Rule, 110),
                (GrammarNonTerminals::StartDef, 112),
                (GrammarNonTerminals::TokenDef, 111),
                (GrammarNonTerminals::TokenTypeDef, 114),
                (GrammarNonTerminals::UserDataDef, 115),
                (GrammarNonTerminals::_GrammarLine_Plus31, 130),
            ],
            &[],
            &[],
            &[],
            &[],
        ];
        const RUSTYLR_REDUCE_MAP: &[&[(u8, u8)]] = &[
            &[],
            &[(0, 2)],
            &[(0, 1)],
            &[],
            &[(1, 49)],
            &[(2, 11)],
            &[],
            &[(2, 11)],
            &[],
            &[(3, 11)],
            &[],
            &[(4, 51)],
            &[(4, 50)],
            &[(5, 55)],
            &[(4, 8)],
            &[],
            &[(4, 9)],
            &[(4, 52)],
            &[(5, 54)],
            &[(4, 53)],
            &[],
            &[(3, 10)],
            &[(3, 16)],
            &[(6, 56)],
            &[(3, 12)],
            &[(3, 13)],
            &[(3, 14)],
            &[(3, 15)],
            &[],
            &[(3, 28)],
            &[(3, 27)],
            &[(3, 17)],
            &[],
            &[(3, 18)],
            &[(6, 57)],
            &[],
            &[(2, 18)],
            &[(4, 51)],
            &[(5, 55)],
            &[],
            &[(2, 10)],
            &[(2, 16)],
            &[(7, 7)],
            &[(2, 12)],
            &[(2, 13)],
            &[(2, 14)],
            &[(2, 15)],
            &[],
            &[(2, 28)],
            &[(2, 27)],
            &[(2, 17)],
            &[],
            &[(8, 0)],
            &[(1, 49)],
            &[(9, 3)],
            &[(7, 46)],
            &[(7, 6)],
            &[(1, 48)],
            &[(7, 47)],
            &[(9, 20)],
            &[(9, 19)],
            &[(9, 5)],
            &[(9, 4)],
            &[(10, 29)],
            &[(10, 30)],
            &[],
            &[],
            &[(11, 58)],
            &[(11, 59)],
            &[(11, 60)],
            &[(11, 61)],
            &[(11, 62)],
            &[(11, 63)],
            &[(11, 64)],
            &[(11, 65)],
            &[(11, 66)],
            &[(11, 67)],
            &[(11, 68)],
            &[(11, 69)],
            &[(11, 70)],
            &[(11, 71)],
            &[(11, 72)],
            &[(11, 73)],
            &[(11, 74)],
            &[(11, 75)],
            &[],
            &[(8, 21)],
            &[(11, 76)],
            &[(12, 22)],
            &[(11, 77)],
            &[],
            &[],
            &[(8, 23)],
            &[],
            &[],
            &[(8, 24)],
            &[],
            &[],
            &[(8, 25)],
            &[],
            &[],
            &[(8, 26)],
            &[],
            &[],
            &[(8, 32)],
            &[],
            &[],
            &[(8, 33)],
            &[],
            &[(8, 34)],
            &[(8, 35)],
            &[(8, 36)],
            &[(8, 37)],
            &[(8, 38)],
            &[(8, 39)],
            &[(8, 40)],
            &[],
            &[(12, 28)],
            &[(4, 51)],
            &[(5, 55)],
            &[],
            &[(12, 10)],
            &[(12, 27)],
            &[],
            &[(8, 31)],
            &[(8, 41)],
            &[(8, 42)],
            &[(8, 43)],
            &[(8, 44)],
            &[(13, 78)],
            &[(13, 79)],
            &[],
            &[],
            &[(13, 45)],
        ];
        const RUSTYLR_RULESET_MAP: &[&[(u8, u8)]] = &[
            &[],
            &[(0, 1)],
            &[(1, 1)],
            &[(0, 2)],
            &[(0, 3)],
            &[(7, 1), (11, 1)],
            &[(7, 2)],
            &[(11, 1)],
            &[(18, 1)],
            &[(11, 1)],
            &[(18, 1)],
            &[(10, 1)],
            &[(50, 1)],
            &[(10, 2)],
            &[(8, 1), (9, 1)],
            &[(9, 2)],
            &[(9, 3)],
            &[(52, 1)],
            &[(53, 1), (54, 1)],
            &[(53, 2)],
            &[(10, 3)],
            &[(10, 4)],
            &[(16, 1)],
            &[(12, 1), (13, 1), (14, 1), (15, 1), (17, 1), (56, 1)],
            &[(12, 2)],
            &[(13, 2)],
            &[(14, 2)],
            &[(15, 2)],
            &[(17, 2)],
            &[(28, 1)],
            &[(27, 1)],
            &[(17, 3)],
            &[(18, 2), (57, 1)],
            &[(18, 3)],
            &[(12, 1), (13, 1), (14, 1), (15, 1), (17, 1), (57, 2)],
            &[(18, 2), (57, 1)],
            &[(18, 3)],
            &[(10, 1)],
            &[(10, 2)],
            &[(10, 3)],
            &[(10, 4)],
            &[(16, 1)],
            &[(7, 3), (12, 1), (13, 1), (14, 1), (15, 1), (17, 1)],
            &[(12, 2)],
            &[(13, 2)],
            &[(14, 2)],
            &[(15, 2)],
            &[(17, 2)],
            &[(28, 1)],
            &[(27, 1)],
            &[(17, 3)],
            &[(0, 4), (3, 1)],
            &[(0, 5)],
            &[(3, 2)],
            &[(3, 3)],
            &[(46, 1)],
            &[(6, 1), (12, 1), (13, 1), (14, 1), (15, 1), (17, 1)],
            &[(47, 1), (48, 1)],
            &[(47, 2)],
            &[(5, 1)],
            &[(19, 1)],
            &[(5, 2)],
            &[(4, 1)],
            &[(29, 1)],
            &[(30, 1)],
            &[(21, 1)],
            &[(21, 2)],
            &[(58, 1)],
            &[(59, 1)],
            &[(60, 1)],
            &[(61, 1)],
            &[(62, 1)],
            &[(63, 1)],
            &[(64, 1)],
            &[(65, 1)],
            &[(66, 1)],
            &[(67, 1)],
            &[(68, 1)],
            &[(69, 1)],
            &[(70, 1)],
            &[(71, 1)],
            &[(72, 1)],
            &[(73, 1)],
            &[(74, 1)],
            &[(75, 1)],
            &[(21, 3)],
            &[(21, 4)],
            &[(76, 1)],
            &[(22, 1), (77, 1)],
            &[(77, 2)],
            &[(23, 1)],
            &[(23, 2)],
            &[(23, 3)],
            &[(24, 1)],
            &[(24, 2)],
            &[(24, 3)],
            &[(25, 1)],
            &[(25, 2)],
            &[(25, 3)],
            &[(26, 1)],
            &[(26, 2)],
            &[(26, 3)],
            &[(32, 1)],
            &[(32, 2)],
            &[(32, 3)],
            &[(33, 1)],
            &[(33, 2)],
            &[(33, 3)],
            &[(34, 1)],
            &[(34, 2)],
            &[(35, 1)],
            &[(36, 1)],
            &[(37, 1)],
            &[(38, 1)],
            &[(39, 1)],
            &[(40, 1)],
            &[(31, 1)],
            &[(28, 1)],
            &[(10, 1)],
            &[(10, 2)],
            &[(10, 3)],
            &[(10, 4)],
            &[(27, 1)],
            &[(31, 2)],
            &[(31, 3)],
            &[(41, 1)],
            &[(42, 1)],
            &[(43, 1)],
            &[(44, 1)],
            &[(78, 1), (79, 1)],
            &[(79, 2)],
            &[(80, 1)],
            &[(80, 2)],
            &[(45, 1)],
        ];
        const RUSTYLR_RULESET_SHIFTED0_MAP: &[u8] = &[
            0, 1, 2, 2, 3, 2, 4, 2, 5, 2, 5, 6, 2, 7, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 9,
            2, 2, 2, 4, 2, 2, 4, 2, 6, 7, 2, 2, 2, 2, 2, 2, 2, 2, 9, 2, 2, 2, 2, 2, 10, 2, 2, 2,
            11, 2, 12, 2, 2, 2, 2, 2, 2, 13, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 14, 2, 2, 2, 2, 13, 2, 2, 13, 2, 2, 13, 2, 2, 13, 2, 2, 13, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 9, 2, 6, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 15, 2, 2, 2, 2,
        ];
        let states: Vec<GrammarState> = RUSTYLR_SHIFT_TERM_MAP
            .iter()
            .zip(
                RUSTYLR_SHIFT_NONTERM_MAP.iter().zip(
                    RUSTYLR_REDUCE_MAP.iter().zip(
                        RUSTYLR_RULESET_MAP
                            .iter()
                            .zip(RUSTYLR_RULESET_SHIFTED0_MAP.iter()),
                    ),
                ),
            )
            .map(
                |(
                    shift_goto_map_term,
                    (shift_goto_map_nonterm, (reduce_map_, (ruleset, ruleset0_id))),
                )| {
                    let mut reduce_map = ::rusty_lr_core::HashMap::default();
                    for (terminal_set_id, ruleid) in reduce_map_.iter() {
                        reduce_map.extend(
                            RUSTYLR_REDUCE_TERMINALS_CACHE[*terminal_set_id as usize]
                                .iter()
                                .map(|term_idx| {
                                    (
                                        __rustylr_terminals[*term_idx as usize].clone(),
                                        *ruleid as usize,
                                    )
                                }),
                        );
                    }
                    let mut ruleset: std::collections::BTreeSet<::rusty_lr_core::ShiftedRuleRef> =
                        ruleset
                            .iter()
                            .map(|(ruleid, shifted)| ::rusty_lr_core::ShiftedRuleRef {
                                rule: *ruleid as usize,
                                shifted: *shifted as usize,
                            })
                            .collect();
                    ruleset.extend(
                        RUSTYLR_RULESET_SHIFTED0_CACHE[*ruleset0_id as usize]
                            .iter()
                            .map(|ruleid| ::rusty_lr_core::ShiftedRuleRef {
                                rule: *ruleid as usize,
                                shifted: 0,
                            }),
                    );
                    GrammarState {
                        shift_goto_map_term: shift_goto_map_term
                            .iter()
                            .map(|(term_idx, goto)| {
                                (
                                    __rustylr_terminals[*term_idx as usize].clone(),
                                    *goto as usize,
                                )
                            })
                            .collect(),
                        shift_goto_map_nonterm: shift_goto_map_nonterm
                            .iter()
                            .map(|(nonterm, goto)| (*nonterm, *goto as usize))
                            .collect(),
                        reduce_map,
                        ruleset,
                    }
                },
            )
            .collect();
        Self { rules, states }
    }
}
// ==============================Generated Codes End===============================
