[package]
name = "rusty_lr"
version = "0.3.3"
edition = "2021"
license = "MIT"
description = "LR(1) parser generator"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[dependencies]
