[package]
name = "rusty_lr"
version = "3.15.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bison-like, GLR, LR(1) and LALR(1) parser generator with custom reduce action"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "bison", "lr", "glr", "compiler"]
categories = ["parsing", "compilers", "parser-implementations"]

[dependencies]
rusty_lr_core = { version = "3.19.0", path = "../rusty_lr_core" }
rusty_lr_derive = { version = "2.22.0", path = "../rusty_lr_derive", optional = true }
rusty_lr_buildscript = { version = "0.40.0", path = "../rusty_lr_buildscript", optional = true }

[features]
default = ["derive"]
fxhash = []
build = ["dep:rusty_lr_buildscript"]
derive = ["dep:rusty_lr_derive"]
tree = [
  "rusty_lr_core/tree",
  "rusty_lr_derive/tree",
  "rusty_lr_buildscript/tree",
]
error = ["rusty_lr_core/error"]
