[package]
name = "rusty_lr"
version = "1.4.0"
edition = "2021"
license = "MIT"
description = "yacc-like, proc-macro based LR(1) and LALR(1) parser generator and code generation"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[dependencies]
rusty_lr_core = "1.2"
rusty_lr_derive = "1.2"
# rusty_lr_core = { path = "../rusty_lr_core" }
# rusty_lr_derive = { path = "../rusty_lr_derive" }

[features]
default = []
fxhash = ["rusty_lr_core/fxhash"]
# default = ["core", "derive"]
# core = ["rusty_lr_core"]
# derive = ["rusty_lr_derive"]
