[package]
name = "rusty_lr_derive"
version = "0.10.0"
edition = "2021"
license = "MIT"
description = "yacc-like, proc-macro based LR(1) and LALR(1) parser generator and code generation"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0"
rusty_lr = { package = "rusty_lr", version = "=0.9.0" }
