[package]
name = "rusty_lr_derive"
version = "1.3.0"
edition = "2021"
license = "MIT"
description = "yacc-like, LR(1) and LALR(1) parser generator and code generation"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
# rusty_lr_parser = { path = "../rusty_lr_parser" }
rusty_lr_parser = "3.0"
