[package]
name = "rusty_lr_core"
version = "3.13.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "core library for rusty_lr"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "bison", "lr", "glr", "compiler"]
categories = ["parsing"]

[dependencies]
rustc-hash = { version = "2.0", optional = true }
termtree = { version = "0.5", optional = true }

[features]
default = []
# use `rustc-hash` crate for hash map
fxhash = ["dep:rustc-hash"]
builder = []
tree = ["dep:termtree"]
error = []
