[package]
name = "rusty_lr_core"
version = "2.0.0"
edition = "2021"
license = "MIT"
description = "yacc-like, LR(1) and LALR(1) parser generator and code generation"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[dependencies]
rustc-hash = { version = "2.0", optional = true }

[features]
default = []
# use `rustc-hash` crate for hash map
fxhash = ["dep:rustc-hash"]
builder = []
