/// A struct to hold information about non-terminal symbols
pub trait NonTerminal<Term> {
    /// Whether this non-terminal is auto-generated by rustylr.
    /// Some non-terminals could be auto-generated to handle regex patterns, character sets, etc.
    fn is_auto_generated(&self) -> bool;
    /// Augmented rule will be generated for entry point of the grammar.
    fn is_augmented(&self) -> bool;
}
