[package]
name = "rusty_lr_expand"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0"
clap = { version = "4.5.7", features = ["derive"] }
# rusty_lr_parser = { path = "../rusty_lr_parser" }
rusty_lr_parser = "1.2"
