[package]
name = "rusty_lr_parser"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "macro line parser for rusty_lr"
repository = "https://github.com/ehwan/RustyLR"
readme = "../README.md"
keywords = ["parser", "yacc", "context-free-grammar", "lr", "compiler"]
categories = ["parsing"]

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0"
rusty_lr_core = "0.9.2"
# rusty_lr_core = { path = "../rusty_lr_core" }
